### ISSUE TITLE
Can't add link to text in homepage header

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#100]
![screen shot 2014-02-03 at 10 39 40](https://f.cloud.github.com/assets/6553938/2063914/cf76a4b6-8cbf-11e3-83a4-c3fc98cd577b.png)
Trying to update text to add a link to another external site - box to add link comes up blank after clicking on 'add link' in toolbar. Image attached..

**Comment by orzubalsky** [comment]
that's strange, it's been working over here. what browser are you using? can you try clearing the browser's cache and refreshing the page?

**Comment by laurabillings** [comment]
i'm using Safari. i cleared the cache and logged in again, and it still
comes up blank ...

On Mon, Feb 3, 2014 at 4:03 PM, or zubalsky notifications@github.comwrote:

> that's strange, it's been working over here. what browser are you using?
> can you try clearing the browser's cache and refreshing the page?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/orzubalsky/tradeschool/issues/100#issuecomment-33968824
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by orzubalsky** [comment]
Is it the same on other browsers?

**Comment by laurabillings** [comment]
Yes. I downloaded Chrome and tried again. Same blank box. Image attached...

On Fri, Feb 14, 2014 at 2:19 AM, or zubalsky notifications@github.comwrote:

> Is it the same on other browsers?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/orzubalsky/tradeschool/issues/100#issuecomment-35049621
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by orzubalsky** [comment]
Eek! I don't know why it doesn't work. Have you tried it on other computers? Are other organizers having the same problem? It's hard to debug since it's working over here.

**Comment by laurabillings** [comment]
:s No one else has mentioned it to me.... a friend said it might be
something to do with multiple google log-ins? Could this be the case?

On Sat, Mar 1, 2014 at 5:57 AM, or zubalsky notifications@github.comwrote:

> Eek! I don't know why it doesn't work. Have you tried it on other
> computers? Are other organizers having the same problem? It's hard to debug
> since it's working over here.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/orzubalsky/tradeschool/issues/100#issuecomment-36417306
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by dnephin** [comment]
Is this still an issue? some things you can try:
1. Try the "add link" over at the tiny_mce example site (http://www.tinymce.com/tryit/3_x/full.php). It's possible that this bug was fixed in tiny_mce in one of the latest releases (we have version 3.5.8, and 3.5.10 is the latest in that series). Or it could be that it's just our use of that version.
2. In chrome you can press `Ctrl + Shift + J` which will open the developer console. If you do this in both windows (the main tradeschool admin window and the popup window that comes up when you click on add link), it might contain errors messages that could help debug the problem. If you see any red text in there you can add it to this ticket.

**Comment by laurabillings** [comment]
Thanks Daniel! It seems to be working again now - I don't know what
happened but I think it is fixed. I will use your suggestions if it become
an issue again :)

On Sun, Apr 20, 2014 at 4:05 PM, Daniel Nephin notifications@github.comwrote:

> Is this still an issue? some things you can try:
> 
>    1.
> 
>    Try the "add link" over at the tiny_mce example site (
>    http://www.tinymce.com/tryit/3_x/full.php). It's possible that this
>    bug was fixed in tiny_mce in one of the latest releases (we have version
>    3.5.8, and 3.5.10 is the latest in that series). Or it could be that it's
>    just our use of that version.
>    2.
> 
>    In chrome you can press Ctrl + Shift + J which will open the developer
>    console. If you do this in both windows (the main tradeschool admin window
>    and the popup window that comes up when you click on add link), it might
>    contain errors messages that could help debug the problem. If you see any
>    red text in there you can add it to this ticket.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/orzubalsky/tradeschool/issues/100#issuecomment-40896723
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by dnephin** [comment]
Cool, good to hear.  We can probably close this issue now.

As a project collaborator are you able to close the issue?

**Comment by laurabillings** [comment]
i think so - have done something, let me know if that's not right

On Sun, Apr 20, 2014 at 4:46 PM, Daniel Nephin notifications@github.comwrote:

> Cool, good to hear. We can probably close this issue now.
> 
> As a project collaborator are you able to close the issue?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/orzubalsky/tradeschool/issues/100#issuecomment-40897624
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by dnephin** [comment]
Yup, that worked, thanks!

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by michellesoto** [comment]
Hello everyone, I'm having the same problem. I have used several computers now (all mac), and tried on safari and chrome but nothing works. i get the same blank box as @laurabillings used to get. Any suggestions on what i could do? thank you

**Comment by laurabillings** [comment]
not sure what changed, but it seems to work on my end now. i cleared the
cache out, it didn't work first time, but seemed to work  after that. it's
a mystery!

On Mon, Jun 9, 2014 at 4:30 PM, michellesoto notifications@github.com
wrote:

> Hello everyone, I'm having the same problem. I have used several computers
> now (all mac), and tried on safari and chrome but nothing works. i get the
> same blank box as @laurabillings https://github.com/laurabillings used
> to get. Any suggestions on what i could do? thank you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orzubalsky/tradeschool/issues/100#issuecomment-45503968
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings
