### ISSUE TITLE
can't submit a reuqest to open a new Trade School

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/tradeschool#102]
Leanne Pedante said: I received an error message when I hit "Submit" on my request to start a trade school. It's something I would love to start up, so if you didn't receive my form, and can let me know how to get through, I would really appreciate it. Thanks!

**Comment by orzubalsky** [comment]
The form works as expected but does not provide feedback upon a successful submission. I changed it so it at least redirects to the homepage for now.
