### ISSUE TITLE
Logo photo flashing on homepage

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#103]
There is only one photo uploaded on the backend, and is set to position '0' 
But on the homepage, the logo alternates with a black square, flashing in and out of view.
![Uploading Screen Shot 2014-02-06 at 10.12.50.png . . .]()

**Comment by orzubalsky** [comment]
What school is this happening in?

**Comment by laurabillings** [comment]
West Norwood

**Comment by orzubalsky** [comment]
No more flashing when there is only one image
