### ISSUE TITLE
Modifying a class

### ISSUE THREAD

**Issue by juanpanadero** [orzubalsky/tradeschool#104]
![image](https://f.cloud.github.com/assets/5169140/2105434/6615e1b0-8f8c-11e3-8d69-dce425493097.jpg)

i was trying to recover a past class and that happen 

thanks for all your work Oz

**Comment by orzubalsky** [comment]
Good catch! What field were you trying to change, and what to? This seems like a problem with the system not understanding one of the characters. It should be easy to fix once I know what it was. 

By the way, my name is Or :)

**Comment by juanpanadero** [comment]
I'm so sorry, of course I know you're Or, totally my bad, well actually the thing is that I have a past class and I want to change the day and send it as pending, all the fields were filled because the class was active before.

So I certanly do not know wich field is the one who has a problem

**Comment by juanpanadero** [comment]
You know what, i try it again and I change the dates and I save the class without probem and already have it as pending but when I try to change it to approved then I have the same error from above

**Comment by juanpanadero** [comment]
hahahaha I'm sorry Or but I see what was the problem, the system shows the error when you're approving a class when the teaches is a student, I don't know how but in the field teaches was a student name and the student doesn't have a register as a teacher, i think I have to add the new teacher right? I mean there's no way to change the status right?
