### ISSUE TITLE
More 'Genre' Colors

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#107]
Maybe three or four more colors to help seperate class types? :) I'm a total data person, and I'm having so much trouble grouping classes together in just 7 categories. If this is useful to anyone, feel free to use these.

Business, Environmental Economics & Social Sciences
    -Taxes
    -Job Hunting & Careers
    -Management & Leadership
    -Marketing & Sales
    -Investing
    -Personal Finance
    -Real Estate
    -Small Business & Entrepreneurship
            -Advocacy
            -Politics
Science, Math, Computers & Technology
    -Nature
    -Outdoors/Wilderness/Camping
    -Wildlife
    -Astronomy & Space
    -Ecosystems
    -Agriculture
    -Forestry
    -Horticulture
    -Chemistry  
Food & Wine
    -International
    -Baking
    -Beverages & Wine
    -Canning & Preserving
    -Cooking Methods, Ingredients, Appliances
    -Desserts
    -Entertaining & Holidays
    -Seasonally & Locally
    -Vegetarian & Vegan
Humanities, Film & Photography
    -Interior Design
    -Fashion
    -Graphic Design (Depends on class)
    -History
    -Film/Movies/TV
    -Music
    -Performing Arts
    -Sculpture
    -Architecture
    -Languages
    -Literature
Crafts, Hobbies & Entertainment
    -Candlemaking
    -Flower Arranging
    -Needlecrafts & Textiles
    -Jewelry
    -Mixed-Media
    -Nail Art
    -Papercrafts & Stamping
    -Puzzles & Games
    -Polymer Clay, Pottery & Ceramics
    -Scrapbooking
    -Soap-Making
Health, Alternative Medicine, Sports & Fitness
    -Holistic
    -Naturopathy
    -Massage/Acupuncture
    -Aromatherapy
    -Energy Healing
    -Herbal
    -Beauty, Grooming & Style 
    -Diets & Weight Loss 
    -Exercise & Fitness 
    -Bike Maintenance & Repair
    -Mental Health 
    -Nutrition 
    -Psychology & Counseling 
        -Safety & First Aid 
Self-Improvement & Reference
        -Death & Grief 
    -Dreams 
-Writing & Research
-Words, Language & Grammar
    -Happiness 
    -Goal Attaining
    -Hypnosis 
    -Journal Writing 
    -Memory Improvement 
    -Motivational 
    -Personal Transformation 
    -Relationships 
    -Self-Esteem 
    -Stress Management
    -Success 
    -Time Management

**Comment by orzubalsky** [comment]
What colors would you like to add? If you give me the html hex codes (i.e. #000000) I can add them.

**Comment by brittanyukulele** [comment]
if it's not too much trouble, can I have the hex codes of the ones you have now?

**Comment by orzubalsky** [comment]
Sure, it's right here-
https://github.com/orzubalsky/tradeschool/blob/master/ts/apps/tradeschool/models.py#L2000

**Comment by brittanyukulele** [comment]
CCCCFF - lavender
989898 - grey
(would yellow work?) FFFF66 - yellow
99FFCC -seafoam

thank yew :)

**Comment by orzubalsky** [comment]
the new colors are there!

**Comment by brittanyukulele** [comment]
just tested the colors

seafoam & yellow are a little too blinding with the white. so sorry, didn't think of that! can we change seafoam to 99CCCC & yellow to navy altogether: 000080?
