### ISSUE TITLE
Translation done, but not showing on the frontend

### ISSUE THREAD

**Issue by RachL** [orzubalsky/tradeschool#109]
The website is now fully translated in French, but even if the default language chosen for the branch is French, the frontend remains English....

**Comment by xthian** [comment]
Hi RachL,

This is Christhian from New York. I usually help all the organizers from Latin America and we have been having the same problem with the Spanish Language. 
Or is working on it and it should hopefully be activated really soon!
(when the whole thing is working, even the back end will be entirely in your language! I've seen it working before when we were testing it.)

**Comment by RachL** [comment]
Hi Christhian,

Thanks for your feedback :) It is really a great news for us to know that this option will be available!

**Comment by orzubalsky** [comment]
YAY! Translations are finally working!

**Comment by RachL** [comment]
Yeaaaah that's soo awesome!

However some words are still not translated, althought they are in Rosetta:
http://awesomescreenshot.com/0ac2fk2l3f
http://awesomescreenshot.com/0c22fkgfa0

Is it a bug or they can't be translated?

**Comment by orzubalsky** [comment]
Thanks! I missed the "I can bring the following" so it'll be an easy fix. The other two things are images but they don't really have to be. 

Let me know if you find more words that aren't translated.

**Comment by RachL** [comment]
@orzubalsky Thanks again for your feedback!

Just a question: I've went to this form: http://tradeschool.coop/start-a-tradeschool/ which is also translated for me except for the images. Does this means that all french people will see it in their own language (if the language is translated)? Then maybe you'll receive some request in other language than english...
