### ISSUE TITLE
Where do I edit emails that go out to students?

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/tradeschool#110]
I was showing TS Los Angeles organizers how to use the backend, but they wanted to edit emails that go out to students, and I couldn't see where to do that... http://tradeschool.coop/admin/

**Comment by RachL** [comment]
Hi Caroline,

If I'm not wrong you have to go to:

Admin > Settings > Branches > City (in that case Los Angeles) > then scroll down and just before the photos you have all the emails.

**Comment by carolinewoolard** [comment]
Under "website content"? @RachL I don't see it! Can you take a screen shot?

**Comment by RachL** [comment]
No under "settings" ;-)
Here is a screen shot:
http://awesomescreenshot.com/0942bj24d2 (click on the screenshot to enlarge)

And here is what I see after clicking on branches:
http://awesomescreenshot.com/09c2bj2k76

and after this action just scroll down. Tell me if it is clear

**Comment by brittanyukulele** [comment]
Something I can finally help with! If you go to Settings: Branches & then click on your branch. Scroll all the way down and you will find the emails. Do they already have classes posted? If so, they will have to add an extra step.

:)

**Comment by brittanyukulele** [comment]
Oops - didn't see the updates. Thanks RachL!

**Comment by carolinewoolard** [comment]
Thanks you two! I'm working on a "how to open a new branch/chapter of TS" here: https://github.com/orzubalsky/tradeschool/wiki/Website-Manual:-How-to-open-a-new-Trade-School-chapter
So feel free to edit/add to it, as you help people @laurabillings @brittanyukulele

**Comment by orzubalsky** [comment]
Just to clarify-

The emails under settings/branches are used when a new class is added. A new class's emails are copied from the branch's emails.

If you want to edit the emails for a specific class, navigate to the form of that specific class and scroll down to the section where the emails are.
