### ISSUE TITLE
Reset password doesn't let someone login

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/tradeschool#111]
Leanne couldn't reset her password, so I gave Leanne a new login, and even then Leanne couldn't login. She ended up using my login to edit her branch. Does anyone else have this problem (no ability to make a new user login, no experience of reset password working?)

**Comment by orzubalsky** [comment]
The problem was that she had multiple users on the same email address. That happened because she submitted the start a ts form many times. I think we should address that problem.
