### ISSUE TITLE
Change the name of the email sender

### ISSUE THREAD

**Issue by RachL** [orzubalsky/tradeschool#113]
Hi Or,

Emails are send with the adress mail@tradeschool.coop

Is it possible to have something else than "mail" as a sender? I'm afraid that students and teachers would see it as a spam in their inbox...

**Comment by brittanyukulele** [comment]
We have been sending out ours (Indianapolis) a bunch, and none have gone to the spam folder so far, just as reassurance. :)

**Comment by orzubalsky** [comment]
When the system was sending emails from alias addresses emails weren't being sent correctly so I set it to mail@tradeschool.coop. It's a valid email address so it shouldn't end up in spam, but we could really use a person who is a mail server expert!

**Comment by RachL** [comment]
@brittanyukulele thanks fr your feedback! Btw we love your organization over here :) We're just following your activity throught your newsletter, but it really seems amazing :)

@orzubalsky thanks for the info Or, let's not change anything then ;)
