### ISSUE TITLE
Password Reset action sends 4 different emails

### ISSUE THREAD

**Issue by lpedante** [orzubalsky/tradeschool#117]
When using the "forgot password" function on the admin site, I receive 4 different emails with 4 different usernames, because my email was used several times during set up to try to create an Organizer. 

However, I'm unable to delete these redundant organizer accounts. I receive a Forbidden error. 

I'm able to log in now, so it's not prohibitive. Thanks!

![capture2](https://f.cloud.github.com/assets/6611930/2111403/05d4b8aa-9011-11e3-93a7-60ef766fc804.JPG)
![organizers](https://f.cloud.github.com/assets/6611930/2111443/7abad3b6-9011-11e3-851e-4ca59f08eb5e.JPG)
![delete](https://f.cloud.github.com/assets/6611930/2111444/7abdae4c-9011-11e3-99fa-070d4042e4ef.JPG)

**Comment by orzubalsky** [comment]
Hi Leanne, thanks for using github!

You got 4 emails because the form to start a trade school was submitted 4 times, and the system created 3 clones of you :) I removed them.
