### ISSUE TITLE
can't change slug

### ISSUE THREAD

**Issue by juanpanadero** [orzubalsky/tradeschool#120]
Can you help me to change the slug, I can't do it for myself, there's an error.
we want to get back the tradeschool.coop/guadalajara

Thanks a lot Or

**Comment by juanpanadero** [comment]
Hey Or,

i need help here :( 
![image](https://f.cloud.github.com/assets/5169140/2149434/84afac48-93f4-11e3-85be-09be5a532baa.jpg)

**Comment by orzubalsky** [comment]
I think it should be okay now. What did you want to change the slug to?
