### ISSUE TITLE
Can't open new branch - error when click on pending branch name

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#121]
Trying to open TS Rotterdam. The organiser has filled in the request to start a TS. Rotterdam is shown in the pending branches. There were 2 Rotterdam branches in pending. I made one of them into 'setting up' and it vanished from the list and now I can't find it anywhere... I clicked on the other pending Rotterdam and got an error message:

IndexError at /admin/tradeschool/pendingbranch/79/
list index out of range
Request Method: GET
Request URL:    http://www.tradeschool.coop/admin/tradeschool/pendingbranch/79/
Django Version: 1.5.1
Exception Type: IndexError
Exception Value:  
list index out of range
Exception Location: /opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/db/models/query.py in **getitem**, line 215
Python Executable:  /usr/bin/python
Python Version: 2.7.3
Python Path:  
['/opt/projects/tse/eggs/MySQL_python-1.2.3-py2.7-linux-x86_64.egg',
 '/opt/projects/tse/eggs/South-0.8.4-py2.7.egg',
 '/opt/projects/tse/eggs/simplejson-3.3.2-py2.7-linux-x86_64.egg',
 '/opt/projects/tse/eggs/PIL-1.1.7-py2.7-linux-x86_64.egg',
 '/opt/projects/tse/eggs/requests-2.2.1-py2.7.egg',
 '/opt/projects/tse/eggs/django_tinymce-1.5.2-py2.7.egg',
 '/opt/projects/tse/eggs/django_flatpages_tinymce-0.1.1-py2.7.egg',
 '/opt/projects/tse/eggs/pytz-2013.9-py2.7.egg',
 '/opt/projects/tse/eggs/django_countries-1.5-py2.7.egg',
 '/opt/projects/tse/eggs/django_grappelli-2.4.8-py2.7.egg',
 '/opt/projects/tse/eggs/feedparser-5.1.3-py2.7.egg',
 '/opt/projects/tse/eggs/django_dajaxice-0.5.5-py2.7.egg',
 '/opt/projects/tse/eggs/python_memcached-1.53-py2.7.egg',
 '/opt/projects/tse/eggs/six-1.5.2-py2.7.egg',
 '/opt/projects/tse/eggs/selenium-2.39.0-py2.7.egg',
 '/opt/projects/tse/eggs/docutils-0.11-py2.7.egg',
 '/opt/projects/tse/eggs/django_debug_toolbar-1.0.1-py2.7.egg',
 '/opt/projects/tse/eggs/django_tastypie-0.9.16-py2.7.egg',
 '/opt/projects/tse/eggs/django_ace-1.0.0-py2.7.egg',
 '/opt/projects/tse/eggs/djangorecipe-1.7-py2.7.egg',
 '/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg',
 '/opt/projects/tse/eggs/zc.recipe.egg-2.0.1-py2.7.egg',
 '/opt/projects/tse/eggs/zc.buildout-2.2.1-py2.7.egg',
 '/opt/projects/tse/eggs/python_dateutil-2.2-py2.7.egg',
 '/opt/projects/tse/eggs/mimeparse-0.1.3-py2.7.egg',
 '/opt/projects/tse/eggs/sqlparse-0.1.10-py2.7.egg',
 '/opt/projects/tse/eggs/setuptools-2.1-py2.7.egg',
 '/opt/projects/tse',
 '/opt/projects/tse/ts',
 '/opt/projects/tse/ts/apps',
 '/opt/projects/tse/parts/django-mailer',
 '/opt/projects/tse/parts/django-chunks',
 '/opt/projects/tse/parts/django-rosetta',
 '/opt/projects/tse/parts/django-rosetta-grappelli',
 '/opt/projects/tse/parts/django-admin-enhancer',
 '/opt/projects/tse/parts/django-admin-enhancer/admin_enhancer',
 '/opt/projects/tse/parts/django-guardian',
 '/opt/projects/tse/parts/johnny-cache',
 '/opt/projects/tse/parts/django-templatesadmin',
 '/opt/projects/tse',
 '/opt/projects/tse/ts',
 '/usr/local/lib/python2.7/dist-packages/distribute-0.7.3-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/setuptools-2.1-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/opt/projects/tse/ts/settings',
 '/opt/projects/tse/ts/settings/..',
 '/opt/projects/tse/ts/settings/../apps',
 '/opt/projects/tse/ts/settings/../libs']
Server time:    Mon, 10 Feb 2014 12:32:50 -0500
Error during template rendering

In template /opt/projects/tse/ts/apps/tradeschool/templates/admin/includes/fieldset.html, error at line 22
list index out of range
12                          <div class="grp-cell l-2c-fluid l-d-4 {{ field.field.name }}{% if field.field.errors %} grp-errors{% endif %}">
13                      {% endif %}
14                          {% if field.is_checkbox %}
15                              <div class="c-1">&nbsp;</div>
16                              <div class="c-2">
17                                  {{ field.field }}{{ field.label_tag|prettylabel }}
18                          {% else %}
19                              <div class="c-1">{{ field.label_tag|prettylabel }}</div>
20                              <div class="c-2">
21                                  {% if field.is_readonly %}
22                                      <p class="grp-readonly">{{ field.contents }}</p>
23                                  {% else %}
24                                      {{ field.field }}
25                                  {% endif %}
26                          {% endif %}
27                              {% if line.fields|length_is:'1' %}{{ line.errors }}{% endif %}
28                              {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.field.errors }}{% endif %}
29                              {% if field.field.help_text %}
30                                  <p class="grp-help">{{ field.field.help_text|safe }}</p>
31                              {% endif %}
32                          </div>
Traceback Switch to copy-and-paste view

/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/core/handlers/base.py in get_response
                    response = response.render() ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/response.py in render
            self.content = self.rendered_content ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/response.py in rendered_content
        content = template.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
            return self._render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/loader_tags.py in render
        return compiled_parent._render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/loader_tags.py in render
        return compiled_parent._render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/loader_tags.py in render
            result = block.nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/loader_tags.py in render
            result = block.nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/defaulttags.py in render
                        nodelist.append(node.render(context)) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/loader_tags.py in render
        return self.render_template(self.template, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/loader_tags.py in render_template
        output = template.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
            return self._render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/defaulttags.py in render
        return strip_spaces_between_tags(self.nodelist.render(context).strip()) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/defaulttags.py in render
                        nodelist.append(node.render(context)) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/defaulttags.py in render
                        nodelist.append(node.render(context)) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/defaulttags.py in render
                return nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/defaulttags.py in render
                return nodelist.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in render
                bit = self.render_node(node, context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render_node
            return node.render(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/debug.py in render
            output = self.filter_expression.resolve(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in resolve
                obj = self.var.resolve(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in resolve
            value = self._resolve_lookup(context) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/template/base.py in _resolve_lookup
                            current = current() ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/contrib/admin/helpers.py in contents
            f, attr, value = lookup_field(field, obj, model_admin) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/contrib/admin/util.py in lookup_field
            value = attr(obj) ...
▶ Local vars
/opt/projects/tse/ts/apps/tradeschool/admin.py in organizer_fullname
        organizer = obj.organizers.all()[0] ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/db/models/query.py in __getitem__
            return list(qs)[0] ...
▶ Local vars
Request information

GET
No GET data
POST
No POST data
FILES
No FILES data
COOKIES
Variable    Value
csrftoken  
'9yKFeYXOaagyxTpxEOgnSmZlnBcrPmOO'
**utma  
'131219530.816226940.1355356323.1390577660.1390583388.198'
sessionid  
'ijw492dvmlqetr6tngxizh3wlt8iyyqe'
_ga 
'GA1.2.816226940.1355356323'
__utmz  
'131219530.1386878674.190.7.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)'
META
Variable    Value
mod_wsgi.listener_port  
'80'
HTTP_REFERER  
'http://www.tradeschool.coop/admin/tradeschool/pendingbranch/'
mod_wsgi.listener_host  
''
SERVER_SOFTWARE 
'Apache/2.2.22 (Ubuntu)'
SCRIPT_NAME 
u''
mod_wsgi.handler_script 
''
SERVER_SIGNATURE  
'<address>Apache/2.2.22 (Ubuntu) Server at www.tradeschool.coop Port 80</address>\n'
REQUEST_METHOD  
'GET'
PATH_INFO  
u'/admin/tradeschool/pendingbranch/79/'
SERVER_PROTOCOL 
'HTTP/1.1'
QUERY_STRING  
''
HTTP_USER_AGENT 
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/7.0.1 Safari/537.73.11'
HTTP_CONNECTION 
'keep-alive'
HTTP_COOKIE 
'csrftoken=9yKFeYXOaagyxTpxEOgnSmZlnBcrPmOO; sessionid=ijw492dvmlqetr6tngxizh3wlt8iyyqe; __utma=131219530.816226940.1355356323.1390577660.1390583388.198; __utmz=131219530.1386878674.190.7.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.2.816226940.1355356323'
SERVER_NAME 
'www.tradeschool.coop'
REMOTE_ADDR 
'89.16.224.130'
mod_wsgi.request_handler  
'wsgi-script'
wsgi.url_scheme 
'http'
PATH_TRANSLATED 
'/opt/projects/tse/bin/django.wsgi/admin/tradeschool/pendingbranch/79/'
SERVER_PORT 
'80'
wsgi.multiprocess  
False
mod_wsgi.input_chunked  
'0'
SERVER_ADDR 
'107.170.26.231'
DOCUMENT_ROOT  
'/opt/projects/tse/ts'
mod_wsgi.process_group  
'tse_prod'
SCRIPT_FILENAME 
'/opt/projects/tse/bin/django.wsgi'
SERVER_ADMIN  
'or@tradeschool.coop'
wsgi.input  
<mod_wsgi.Input object at 0x7f32b8310670>
HTTP_HOST  
'www.tradeschool.coop'
wsgi.multithread  
True
mod_wsgi.callable_object  
'application'
REQUEST_URI 
'/admin/tradeschool/pendingbranch/79/'
HTTP_ACCEPT 
'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8'
wsgi.version  
(1, 1)
GATEWAY_INTERFACE  
'CGI/1.1'
wsgi.run_once  
False
wsgi.errors 
<mod_wsgi.Log object at 0x7f32b83103f0>
REMOTE_PORT 
'4097'
HTTP_ACCEPT_LANGUAGE  
'en-us'
mod_wsgi.version  
(3, 3)
CSRF_COOKIE_USED  
True
mod_wsgi.application_group  
'tradeschool.coop|'
mod_wsgi.script_reloading  
'1'
wsgi.file_wrapper  
''
CSRF_COOKIE 
u'9yKFeYXOaagyxTpxEOgnSmZlnBcrPmOO'
HTTP_ACCEPT_ENCODING  
'gzip, deflate'
Settings
Using settings module ts.settings.server
Setting Value
LOCAL_SETTINGS  
True
GRAPPELLI_INDEX_DASHBOARD  
'ts.dashboard.CustomIndexDashboard'
USE_L10N  
True
USE_THOUSAND_SEPARATOR  
False
CSRF_COOKIE_SECURE  
False
LANGUAGE_CODE  
'en-US'
ROOT_URLCONF  
'ts.urls'
LOGIN_URL  
'/admin'
DEFAULT_CHARSET 
'utf-8'
STATIC_ROOT 
'/opt/projects/tse/ts/static/'
TEMPLATESADMIN_TEMPLATE_DIRS  
('/opt/projects/tse/ts/settings/../apps/branches/',)
ALLOWED_HOSTS  
('.tradeschool.coop',)
MESSAGE_STORAGE 
'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX  
'[Django] '
SEND_BROKEN_LINK_EMAILS 
False
STATICFILES_FINDERS 
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder',
 'django.contrib.staticfiles.finders.DefaultStorageFinder',
 'dajaxice.finders.DajaxiceFinder')
SESSION_CACHE_ALIAS 
'default'
SESSION_COOKIE_DOMAIN  
None
SESSION_COOKIE_NAME 
'sessionid'
ADMIN_FOR  
()
TIME_INPUT_FORMATS  
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M', '%I:%M %p')
DATABASES  
{'default': {'ENGINE': 'django.db.backends.mysql',
             'HOST': '',
             'NAME': 'tradeschool_prod',
             'OPTIONS': {},
             'PASSWORD': u'*******************_',
             'PORT': '',
             'TEST_CHARSET': None,
             'TEST_COLLATION': None,
             'TEST_MIRROR': None,
             'TEST_NAME': None,
             'TIME_ZONE': 'UTC',
             'USER': 'tradeschooler'}}
FILE_UPLOAD_PERMISSIONS 
None
FILE_UPLOAD_HANDLERS  
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE  
'text/html'
ROSETTA_CACHE_NAME  
'rosetta'
APPEND_SLASH  
True
FIRST_DAY_OF_WEEK  
0
DATABASE_ROUTERS  
[]
YEAR_MONTH_FORMAT  
'F Y'
STATICFILES_STORAGE 
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES  
{'default': {'BACKEND': 'johnny.backends.memcached.MemcachedCache',
             'JOHNNY_CACHE': True,
             'LOCATION': ['127.0.0.1:11211']},
 'rosetta': {'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
             'JOHNNY_CACHE': True,
             'LOCATION': '/var/tmp/django_cache'}}
SERVER_EMAIL  
'no-reply@theyoungest.webfactional.com'
SESSION_COOKIE_PATH 
'/'
MIDDLEWARE_CLASSES  
('johnny.middleware.LocalStoreClearMiddleware',
 'johnny.middleware.QueryCacheMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'tradeschool.middleware.BranchMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware')
USE_I18N  
True
THOUSAND_SEPARATOR  
','
SECRET_KEY  
u'**_****************_'
LANGUAGE_COOKIE_NAME  
'django_language'
FILE_UPLOAD_TEMP_DIR  
None
TRANSACTIONS_MANAGED  
False
LOGGING_CONFIG  
'django.utils.log.dictConfig'
TEMPLATE_LOADERS  
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
WSGI_APPLICATION  
None
TEMPLATE_DEBUG  
True
X_FRAME_OPTIONS 
'SAMEORIGIN'
AUTHENTICATION_BACKENDS 
('django.contrib.auth.backends.ModelBackend',)
FORCE_SCRIPT_NAME  
None
USE_X_FORWARDED_HOST  
False
SIGNING_BACKEND 
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE  
False
GOOGLE_ANALYTICS_KEY  
u'**_*****************'
FILE_CHARSET  
'utf-8'
DEBUG  
True
SESSION_FILE_PATH  
None
DEFAULT_FILE_STORAGE  
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS  
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'grappelli.dashboard',
 'grappelli',
 'rosetta-grappelli',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.humanize',
 'django.contrib.redirects',
 'django.contrib.flatpages',
 'flatpages_tinymce',
 'django_ace',
 'templatesadmin',
 'south',
 'pytz',
 'dajaxice',
 'rosetta',
 'admin_enhancer',
 'tradeschool',
 'migration')
LANGUAGES_BIDI  
('he', 'ar', 'fa')
COMMENTS_ALLOW_PROFANITIES  
False
STATICFILES_DIRS  
('/opt/projects/tse/ts/settings/../apps/branches',
 '/opt/projects/tse/ts/settings/../../parts/django-admin-enhancer/admin_enhancer/static')
PREPEND_WWW 
False
SECURE_PROXY_SSL_HEADER 
None
GRAPPELLI_ADMIN_TITLE  
<django.utils.functional.__proxy** object at 0x7f32b8688f90>
SESSION_COOKIE_HTTPONLY 
True
DEBUG_PROPAGATE_EXCEPTIONS  
False
CSRF_COOKIE_DOMAIN  
None
MONTH_DAY_FORMAT  
'F j'
MANAGERS  
(('Or Zubalsky', 'juviley@gmail.com'),)
SESSION_EXPIRE_AT_BROWSER_CLOSE 
False
TIME_FORMAT 
'P'
TEMPLATESADMIN_GROUP  
'translators'
AUTH_USER_MODEL 
'tradeschool.Person'
DATE_INPUT_FORMATS  
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
CSRF_COOKIE_NAME  
'csrftoken'
EMAIL_HOST_PASSWORD 
u'*******************_'
ROSETTA_WSGI_AUTO_RELOAD  
True
STAGE_NAME  
'DEV'
PASSWORD_RESET_TIMEOUT_DAYS 
u'**_****************_'
CACHE_MIDDLEWARE_ALIAS  
'default'
SESSION_SAVE_EVERY_REQUEST  
False
ADMIN_MEDIA_PREFIX  
'/admin/media/'
NUMBER_GROUPING 
0
SESSION_ENGINE  
'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW  
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH  
'/'
ROSETTA_MESSAGES_PER_PAGE  
100
LOGIN_REDIRECT_URL  
'/accounts/profile/'
DECIMAL_SEPARATOR  
'.'
IGNORABLE_404_URLS  
()
LOCALE_PATHS  
('/opt/projects/tse/ts/settings/../locale/',)
JOHNNY_MIDDLEWARE_KEY_PREFIX  
u'**_****************_'
TEMPLATE_STRING_IF_INVALID  
''
BASE_BRANCH_TEMPLATE_DIR  
'/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_base'
LOGOUT_URL  
'/accounts/logout/'
EMAIL_USE_TLS  
False
FIXTURE_DIRS  
('/opt/projects/tse/ts/settings/../apps/tradeschool/fixtures',)
EMAIL_HOST  
'smtp.webfaction.com'
DATE_FORMAT 
'N j, Y'
MEDIA_ROOT  
'/opt/projects/tse/ts/media/'
DEFAULT_EXCEPTION_REPORTER_FILTER  
'django.views.debug.SafeExceptionReporterFilter'
ADMINS  
(('Or Zubalsky', 'juviley@gmail.com'),)
FORMAT_MODULE_PATH  
None
DEFAULT_FROM_EMAIL  
'mail@tradeschool.coop'
MEDIA_URL  
'http://tradeschool.coop/media/'
DATETIME_FORMAT 
'N j, Y, P'
TEMPLATE_DIRS  
('/opt/projects/tse/ts/settings/../apps/branches/',
 '/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_default',
 '/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_base',
 '/opt/projects/tse/ts/settings/../apps/tradeschool/templates',
 '/opt/projects/tse/ts/settings/../templates',
 '/opt/projects/tse/ts/settings/../../parts/django-admin-enhancer/admin_enhancer/templates/')
SITE_ID 
1
DISALLOWED_USER_AGENTS  
()
ALLOWED_INCLUDE_ROOTS  
()
LOGGING 
{'disable_existing_loggers': False,
 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}},
 'handlers': {'console': {'class': 'logging.StreamHandler', 'level': 'DEBUG'},
              'mail_admins': {'class': 'django.utils.log.AdminEmailHandler',
                              'filters': ['require_debug_false'],
                              'level': 'ERROR'}},
 'loggers': {'dajaxice': {'handlers': ['console'],
                          'level': 'ERROR',
                          'propagate': True},
             'django.request': {'handlers': ['mail_admins'],
                                'level': 'ERROR',
                                'propagate': True}},
 'version': 1}
PROJECT_DIR 
'/opt/projects/tse/ts/settings/..'
TEST_RUNNER 
'django.test.simple.DjangoTestSuiteRunner'
SHORT_DATE_FORMAT  
'm/d/Y'
CACHE_MIDDLEWARE_KEY_PREFIX 
u'**_****************_'
TIME_ZONE  
'America/New_York'
FILE_UPLOAD_MAX_MEMORY_SIZE 
2621440
EMAIL_BACKEND  
'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_TABLESPACE  
''
TEMPLATE_CONTEXT_PROCESSORS 
('django.contrib.auth.context_processors.auth',
 'django.core.context_processors.request',
 'django.core.context_processors.i18n',
 'django.core.context_processors.debug',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.tz',
 'django.contrib.messages.context_processors.messages',
 'tradeschool.context_processors.branch',
 'tradeschool.context_processors.google_analytics')
SESSION_COOKIE_AGE  
1209600
SETTINGS_MODULE 
'ts.settings.server'
BRANCH_TEMPLATE_DIR 
'/opt/projects/tse/ts/settings/../apps/branches/'
USE_ETAGS  
False
LANGUAGES  
(('en', 'English'),
 ('es_es', 'Spanish (Spain)'),
 ('es_mx', 'Spanish (Mexico)'),
 ('es_us', 'Spanish (US)'),
 ('es_ar', 'Spanish (Argentina)'),
 ('es_cl', 'Spanish (Chile)'),
 ('es_ec', 'Spanish (Ecuador)'),
 ('es_pr', 'Spanish (Puerto Rico)'),
 ('es_ve', 'Spanish (Venezuela)'),
 ('de_de', 'German'),
 ('ms_sg', 'Malay'),
 ('zh_sg', 'Chinese (Singapore)'),
 ('it_it', 'Italian'),
 ('tl', 'Tagalog'),
 ('fr_fr', 'French'),
 ('nl_nl', 'Dutch'),
 ('th', 'Thai'),
 ('pt_br', 'Portuguese'),
 ('el_gr', 'Greek'),
 ('ru_ru', 'Russian'),
 ('zh_cn', 'Chinese (China)'),
 ('vi', 'Vietnamese'),
 ('ta_sg', 'Tamil (Singapore)'))
DEFAULT_INDEX_TABLESPACE  
''
INTERNAL_IPS  
('127.0.0.1',)
STATIC_URL  
'http://tradeschool.coop/static/'
EMAIL_PORT  
25
USE_TZ  
True
SHORT_DATETIME_FORMAT  
'm/d/Y P'
PASSWORD_HASHERS  
u'**_****************_'
TINYMCE_DEFAULT_CONFIG  
{'plugins': 'table,spellchecker,paste,searchreplace', 'theme': 'advanced'}
ABSOLUTE_URL_OVERRIDES  
{}
CACHE_MIDDLEWARE_SECONDS  
600
DATETIME_INPUT_FORMATS  
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d %I:%M %p',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
DEFAULT_BRANCH_TEMPLATE_DIR 
'/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_default'
ROSETTA_STORAGE_CLASS  
'rosetta.storage.CacheRosettaStorage'
EMAIL_HOST_USER 
'theyoungest'
PROFANITIES_LIST  
u'**_*****************'

**Comment by orzubalsky** [comment]
@laurabillings You should see the Rotterdam school in your drop down menu at the top when you log in now. There are a few things to remember to do when helping someone set up a new school, which might not be trivial. @carolinewoolard started a wiki page on how to do it-https://github.com/orzubalsky/tradeschool/wiki/Website-Manual:-How-to-open-a-new-Trade-School-chapter

Feel free to edit and add to it :)
