### ISSUE TITLE
Student registration freezes in the chihuahua branch

### ISSUE THREAD

**Issue by xthian** [orzubalsky/tradeschool#122]
When a student registers for a class in the Chichuahua branch, the loading bar continues to do it's thing, but never shows the student that they've officially been registered. This is all you see indefinitely: 
![screen shot 2014-02-11 at 9 26 01 pm](https://f.cloud.github.com/assets/2106579/2144699/fbdfab0e-938d-11e3-9ca9-9031f4fb11ae.png)

**Comment by xthian** [comment]
The system registered me, but never sent me an e-mail. I know this because I see the registration in the back, and also because I try signing up for classes in other branches where the whole process was fluid and I received the registration emails.

**Comment by orzubalsky** [comment]
There was a problem handling certain characters when creating the email that is sent. Should be fixed now!
