### ISSUE TITLE
Unregister Link Error?

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#123]
http://tradeschool.coop/indianapolis/class/cross-stitch-101/unregister/jess is going to the homepage of the website and not unregistering the student, or it  is giving them an error. I will try and get a screenshot of the error.

**Comment by orzubalsky** [comment]
It'd be good to see a screenshot. When I visit this link I get the normal screen-

![screen shot 2014-02-13 at 9 19 06 pm](https://f.cloud.github.com/assets/1025973/2167617/66ab489e-951e-11e3-8e4c-f438615ac846.png)
