### ISSUE TITLE
Adding Pending Class Edmonton

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#124]
AttributeError at /admin/tradeschool/pendingcourse/add/
'NoneType' object has no attribute 'iteritems'
Request Method: POST
Request URL:    http://tradeschool.coop/admin/tradeschool/pendingcourse/add/
Django Version: 1.5.1
Exception Type: AttributeError
Exception Value:  
'NoneType' object has no attribute 'iteritems'
Exception Location: /opt/projects/tse/ts/apps/tradeschool/models.py in populate_notifications, line 2362
Python Executable:  /usr/bin/python
Python Version: 2.7.3

**Comment by orzubalsky** [comment]
Should work now. For some reason branch's emails aren't being generated when new branches are added. I'll open a separate issue for that.
