### ISSUE TITLE
Edit HTML Template results in blank page

### ISSUE THREAD

**Issue by lpedante** [orzubalsky/tradeschool#126]
Hi, there. I'm trying to edit my site's CSS but when I click Edit HTML Template, I just come to a blank page. The URL is http://tradeschool.coop/admin/templatesadmin/ and I'm using Chrome. 

![edithtml](https://f.cloud.github.com/assets/6611930/2182642/9f2dde58-9793-11e3-817f-c898956822f0.JPG)

**Comment by orzubalsky** [comment]
The LA files weren't generated but they should be there now.
