### ISSUE TITLE
Changes not reflecting - editing pages

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#133]
Hey Or! Just wondering, do we have to ask you each time we make a change so you can refresh it? I am noticing that when I am adding headers and stuff to my about page, they are not registering after I save. Is this because you have to refresh it? Thanks!

**Comment by orzubalsky** [comment]
The changes you make to pages should be reflected when you hit save. What's missing? Maybe something is broken in the code of that specific page? I can take a look.

**Comment by brittanyukulele** [comment]
The headings are not reflecting. I changed ours to make certain types bigger, etc on our about page. http://tradeschool.coop/indianapolis/page/about/

**Comment by orzubalsky** [comment]
Oh, I see what you mean. We would need to add CSS to account for the styles that are produced by this editor. Thanks for noticing this!
