### ISSUE TITLE
Reminder emails being sent out for rejected classes

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#134]
I created a test class on Trade School West Norwood - and rejected it on the admin end so it isn't live. But I have just got a reminder email for it... 

Hi Laura,

We're excited to see you tomorrow!

Your class, "TEST" is scheduled for March 5, 2014, 2:30 p.m..

**Comment by orzubalsky** [comment]
Fixed it. Thanks Laura!
