### ISSUE TITLE
Logging in as other schools

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#137]
I am confused on how to look at other schools when helping them? They have to grant us permission correct?

**Comment by orzubalsky** [comment]
Yes, ask the organizer from the other school to
1. Go to http://tradeschool.coop/admin/tradeschool/branch and click on their school.
2. Scroll down to the organizers section.
3. Find your username on the left (under "Available Organizers") and click on the arrow pointing right to move it to "Chosen Organizers"
4. Click on save

After that you should be able to click on the school name on the top bar, choose the other school, and click on "change branch".

Let me know if you have any questions!
