### ISSUE TITLE
gmt time problems

### ISSUE THREAD

**Issue by harleytsberlin** [orzubalsky/tradeschool#138]
Hey!
All our students get reminder emails with the wrong time and I think the reason is that on the time settings there is no time added to alter the GMT time (it says + 00:00).
I'm not sure where I would go to add the appropriate amount for Berlin, which is 1 hour later than GMT.
However, the emails sent say the classes are on average 5 hours earlier than they actually start (most of our classes start at 7pm, the emails have been saying 2pm instead), so I'm confused because then that means somewhere there is time being added to GMT, but not the right amount... does that make sense?
Thanks for the help!
≥Ö‿Ö≤

**Comment by RachL** [comment]
Hey @harleytsberlin I'm glad you bring that up as I have the same problem in Paris! :-)

But I know how to change the Timezone: you need to go to your backend, then:

Branches > Berlin > Timezone (in Basic info) > safe

On the problem of 5 hours delay I don't have an answer and I'm also looking for one. First I thought that my mistake was to set Paris' timezone to "+1", but it is not a GMT time but an Etc/GMT time, which is according to my google research another way of accounting time.

So I think that the timezone for Paris and Berlin is Etc/GMT-1, but I really would like someone to confirm my research :)

Thanks,

Rachel

**Comment by orzubalsky** [comment]
Hi everyone,

There was a problem with the times in emails not being calculated correctly but I fixed it yesterday. Can you check again whether the problem still persists?
