### ISSUE TITLE
Password Reset not working for Arda

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#140]
Hey there! I've been trying to help arda login to the backend.

From: mail@tradeschool.coop

Subject: Password reset on tradeschool

Date: 10 maart 2014 14:45:57 GMT+01:00

To: arda@w139.nl

You're receiving this e-mail because you requested a password reset for your user account at tradeschool.

Please go to the following page and choose a new password:

http://tradeschool.coop/reset/9ff-3ps-d32f57feb5d9d2680f31/

Your username, in case you've forgotten: arda

Thanks for using our site!

The tradeschool team

We have reset her PW several times but it's still not working. I reset her pw to test123 and still won't let me. Her email is  arda arda@w139.nl .

**Comment by brittanyukulele** [comment]
here is error code

IndexError at /admin/
list index out of range

Request Method:
GET 

Request URL:
http://tradeschool.coop/admin/ 

Django Version:
1.5.1 

Exception Type:
IndexError 

Exception Value:
list index out of range

Exception Location:
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/db/models/query.py in **getitem**, line 215 

Python Executable:
/usr/bin/python 

Python Version:
2.7.3

**Comment by orzubalsky** [comment]
Hi Brittany,

What school is Arda organizing? I see that she's a part of Indianapolis.

**Comment by brittanyukulele** [comment]
She is supposed to be in Amsterdam

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy
(317) 366-6938
http://tradeschool.coop/Indianapolishttp://tradeschool.coop/Indianapolis/class

**Comment by orzubalsky** [comment]
It seems like she had another user? I connected the second user with Amsterdam and she should be able to log in now.
