### ISSUE TITLE
What is the link to "offer a class"? ..so that we can activate the seasson

### ISSUE THREAD

**Issue by LaTrueca** [orzubalsky/tradeschool#142]
Hi Or, I've been looking at the Website Handbook that Rachel shared with us https://docs.google.com/document/d/1z6CIPNgXmVkZjbYFZ5yy2n2JvhYDoF6uIaeYByjrpXQ/edit
to see if I could find the link to where teachers would go to when then want to offer an activity. But the one I found in the handbook is:
  6a. Test the times lots on the back end:
  http://tradeschool.coop/CITYNAME/class/add
  And have the organizer fill it out so they can test the system with a real email address!

And that link sends you to the old form...
Could you send us the new link so that we can open our seasson and put "offer an activity" in the front page.?

Thankyou!!

**Comment by orzubalsky** [comment]
What do you mean by the new link? Are you referring to this kind of page- http://tradeschool.coop/newyork/page/teacher-info

**Comment by LaTrueca** [comment]
Yes!, I'm sorry if I wasn't clear...
how do we make that page to appear first (when someone clics on "offer an
activity" in the frontal page)...and then, from there go to writting the
class information?

LA TRUECA
www.latrueca.tk

2014-03-11 23:29 GMT-05:00 or zubalsky notifications@github.com:

**Comment by orzubalsky** [comment]
You would need to link to the teacher info page:
1. Log in to the admin backend
2. Click on Branches and click on your school
3. Edit the link in the intro section and change it to ../school_name/page/teacher-info
4. If you want to edit the content of that page, go to http://tradeschool.coop/admin/tradeschool/page/ and edit the teacher info page.

If you change the URL, make sure to update the link in the intro text box to the new one.
