### ISSUE TITLE
Cannot add links, upload pictures (pop up window in the backend open but no editing possible)

### ISSUE THREAD

**Issue by narmada4us** [orzubalsky/tradeschool#143]
Hello, 
my computer settings are ok. Help please! 

![screen shot 2014-03-18 at 7 33 02 pm](https://f.cloud.github.com/assets/6509001/2470873/3cc23c42-b01a-11e3-8862-01607e3e93f8.png)

**Comment by orzubalsky** [comment]
Hi Narmada! This looks like the same problem that Laura was having and logged on issue #100 . I wonder if she figured it out. I'm closing this one so the discussion can happen in one place.
