### ISSUE TITLE
How to download student / teacher emails?

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#165]
Hello - I'd like to download a list of all contacts for the Trade School to import them to Mailchimp for sending newsletters. The old website let you download a CSV file, but I can't find that option on the new system? Thanks!

**Comment by brittanyukulele** [comment]
hi laura! 

go to students > select all > a box will show at the bottom that says select all XXXX students > click the drop down box > choose CSV export

let me know if that helps!

**Comment by laurabillings** [comment]
Thanks Brittany! Will give that a go.
