### ISSUE TITLE
How to change main branch email?

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#167]
Hello
westminster@tradeschool.coop is currently forwarding to tradeschoollondon@gmail.com

We'd like to change it to go to nkechi.ebite@hubwestminster.net

But I can't see on the branch pages where this is possible to change?

Thanks!

**Comment by brittanyukulele** [comment]
Hey Laura!

In the admin backend go to 'branches' under settings > click your school > you can change your email address under contact info

let me now if that doesn't help. thank you!

**Comment by laurabillings** [comment]
Thanks Brittany

The main email is showing as westminster@tradeschool.coop which is
currently diverting to tradeschoollondon@gmail.com. But we'd like to change
that to nkechi.ebite@hubwestminster.net
Not sure how to manage that?
Best
Laura

On Thu, May 15, 2014 at 9:34 PM, brittanyukulele
notifications@github.comwrote:

> Hey Laura!
> 
> In the admin backend go to 'branches' under settings > click your school >
> you can change your email address under contact info
> 
> let me now if that doesn't help. thank you!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/orzubalsky/tradeschool/issues/167#issuecomment-43261352
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by brittanyukulele** [comment]
Hi Laura!

If you can add me as an organizer I can get in the backend and look at it for ya! Thanks. :)

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy http://twitter.com/tradeschoolindy 
(317) 366-6938

http://tradeschool.coop/Indianapolis http://tradeschool.coop/Indianapolis/class

**Comment by laurabillings** [comment]
Hey Brittany

Sorry - how do I do this?

On Mon, Jun 2, 2014 at 9:34 PM, brittanyukulele notifications@github.com
wrote:

> Hi Laura!
> 
> If you can add me as an organizer I can get in the backend and look at it
> for ya! Thanks. :)
> 
> Brittany West
> Co-Founder Trade School Indy / @tradeschoolindy <
> http://twitter.com/tradeschoolindy>
> (317) 366-6938
> 
> http://tradeschool.coop/Indianapolis <
> http://tradeschool.coop/Indianapolis/class>
> 
> From: laurabillings [mailto:notifications@github.com]
> Sent: Monday, May 26, 2014 3:27 AM
> To: orzubalsky/tradeschool
> Cc: brittanyukulele
> Subject: Re: [tradeschool] How to change main branch email? (#167)
> 
> Thanks Brittany
> 
> The main email is showing as westminster@tradeschool.coop which is
> currently diverting to tradeschoollondon@gmail.com. But we'd like to
> change
> that to nkechi.ebite@hubwestminster.net
> Not sure how to manage that?
> Best
> Laura
> 
> On Thu, May 15, 2014 at 9:34 PM, brittanyukulele
> notifications@github.comwrote:
> 
> > Hey Laura!
> > 
> > In the admin backend go to 'branches' under settings > click your school
> > 
> > you can change your email address under contact info
> > 
> > let me now if that doesn't help. thank you!
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-43261352>
> > 
> > .
> 
> ## 
> 
> Laura Billings
> 
> 07789 214 934
> @laurabillings https://twitter.com/laurabillings
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44163843>
> . <
> https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxNjcwODQ0MywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--a26764b3bbe4e8da5a7ce907c32e3ec29ab2736d.gif>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44887458
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by brittanyukulele** [comment]
no prob!

in admin go to people > settings > branches > click on your branch > scroll down to organizers > find my name under available organizers > Brittany > add to chosen organizers

let me know when you do that and I will take a look!

**Comment by laurabillings** [comment]
done!

On Fri, Jun 6, 2014 at 9:33 PM, brittanyukulele notifications@github.com
wrote:

> no prob!
> 
> in admin go to people > settings > branches > click on your branch >
> scroll down to organizers > find my name under available organizers >
> Brittany > add to chosen organizers
> 
> let me know when you do that and I will take a look!
> 
> From: laurabillings [mailto:notifications@github.com]
> Sent: Friday, June 06, 2014 1:34 PM
> To: orzubalsky/tradeschool
> Cc: brittanyukulele
> Subject: Re: [tradeschool] How to change main branch email? (#167)
> 
> Hey Brittany
> 
> Sorry - how do I do this?
> 
> On Mon, Jun 2, 2014 at 9:34 PM, brittanyukulele notifications@github.com
> 
> wrote:
> 
> > Hi Laura!
> > 
> > If you can add me as an organizer I can get in the backend and look at
> > it
> > for ya! Thanks. :)
> > 
> > Brittany West
> > Co-Founder Trade School Indy / @tradeschoolindy <
> > http://twitter.com/tradeschoolindy>
> > (317) 366-6938
> > 
> > http://tradeschool.coop/Indianapolis <
> > http://tradeschool.coop/Indianapolis/class>
> > 
> > From: laurabillings [mailto:notifications@github.com]
> > Sent: Monday, May 26, 2014 3:27 AM
> > To: orzubalsky/tradeschool
> > Cc: brittanyukulele
> > Subject: Re: [tradeschool] How to change main branch email? (#167)
> > 
> > Thanks Brittany
> > 
> > The main email is showing as westminster@tradeschool.coop which is
> > currently diverting to tradeschoollondon@gmail.com. But we'd like to
> > change
> > that to nkechi.ebite@hubwestminster.net
> > Not sure how to manage that?
> > Best
> > Laura
> > 
> > On Thu, May 15, 2014 at 9:34 PM, brittanyukulele
> > notifications@github.comwrote:
> > 
> > > Hey Laura!
> > > 
> > > In the admin backend go to 'branches' under settings > click your
> > > school
> > > 
> > > you can change your email address under contact info
> > > 
> > > let me now if that doesn't help. thank you!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-43261352>
> > 
> > > .
> > 
> > ## 
> > 
> > Laura Billings
> > 
> > 07789 214 934
> > @laurabillings https://twitter.com/laurabillings
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44163843>
> > 
> > . <
> > 
> > https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxNjcwODQ0MywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--a26764b3bbe4e8da5a7ce907c32e3ec29ab2736d.gif>
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44887458>
> > 
> > .
> 
> ## 
> 
> Laura Billings
> 
> 07789 214 934
> @laurabillings https://twitter.com/laurabillings
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45363386>
> . <
> https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxNzY5NTIyMywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--3ebe8632c6740dfc26fccfec2533943edc1d1d95.gif>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45381243
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by brittanyukulele** [comment]
hey laura!

I don't see london as an option. :( I can also login to your backend if you let me know your username/pw. Thank you!

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy http://twitter.com/tradeschoolindy 
(317) 366-6938

http://tradeschool.coop/Indianapolis http://tradeschool.coop/Indianapolis/class

**Comment by laurabillings** [comment]
hey Britanny

I added you to Westminster - can you see that?
there were also a couple of Brittany usernames in the list, i might not
have added the right one..?

On Mon, Jun 16, 2014 at 3:33 PM, brittanyukulele notifications@github.com
wrote:

> hey laura!
> 
> I don't see london as an option. :( I can also login to your backend if
> you let me know your username/pw. Thank you!
> 
> Brittany West
> Co-Founder Trade School Indy / @tradeschoolindy <
> http://twitter.com/tradeschoolindy>
> (317) 366-6938
> 
> http://tradeschool.coop/Indianapolis <
> http://tradeschool.coop/Indianapolis/class>
> 
> From: laurabillings [mailto:notifications@github.com]
> Sent: Wednesday, June 11, 2014 4:05 PM
> To: orzubalsky/tradeschool
> Cc: brittanyukulele
> Subject: Re: [tradeschool] How to change main branch email? (#167)
> 
> done!
> 
> On Fri, Jun 6, 2014 at 9:33 PM, brittanyukulele notifications@github.com
> 
> wrote:
> 
> > no prob!
> > 
> > in admin go to people > settings > branches > click on your branch >
> > scroll down to organizers > find my name under available organizers >
> > Brittany > add to chosen organizers
> > 
> > let me know when you do that and I will take a look!
> > 
> > From: laurabillings [mailto:notifications@github.com]
> > Sent: Friday, June 06, 2014 1:34 PM
> > To: orzubalsky/tradeschool
> > Cc: brittanyukulele
> > Subject: Re: [tradeschool] How to change main branch email? (#167)
> > 
> > Hey Brittany
> > 
> > Sorry - how do I do this?
> > 
> > On Mon, Jun 2, 2014 at 9:34 PM, brittanyukulele <
> > notifications@github.com>
> > 
> > wrote:
> > 
> > > Hi Laura!
> > > 
> > > If you can add me as an organizer I can get in the backend and look at
> > > it
> > > for ya! Thanks. :)
> > > 
> > > Brittany West
> > > Co-Founder Trade School Indy / @tradeschoolindy <
> > > http://twitter.com/tradeschoolindy>
> > > (317) 366-6938
> > > 
> > > http://tradeschool.coop/Indianapolis <
> > > http://tradeschool.coop/Indianapolis/class>
> > > 
> > > From: laurabillings [mailto:notifications@github.com]
> > > Sent: Monday, May 26, 2014 3:27 AM
> > > To: orzubalsky/tradeschool
> > > Cc: brittanyukulele
> > > Subject: Re: [tradeschool] How to change main branch email? (#167)
> > > 
> > > Thanks Brittany
> > > 
> > > The main email is showing as westminster@tradeschool.coop which is
> > > currently diverting to tradeschoollondon@gmail.com. But we'd like to
> > > change
> > > that to nkechi.ebite@hubwestminster.net
> > > Not sure how to manage that?
> > > Best
> > > Laura
> > > 
> > > On Thu, May 15, 2014 at 9:34 PM, brittanyukulele
> > > notifications@github.comwrote:
> > > 
> > > > Hey Laura!
> > > > 
> > > > In the admin backend go to 'branches' under settings > click your
> > > > school
> > > > 
> > > > you can change your email address under contact info
> > > > 
> > > > let me now if that doesn't help. thank you!
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-43261352>
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Laura Billings
> > > 
> > > 07789 214 934
> > > @laurabillings https://twitter.com/laurabillings
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44163843>
> > 
> > > . <
> > 
> > https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxNjcwODQ0MywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--a26764b3bbe4e8da5a7ce907c32e3ec29ab2736d.gif>
> > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44887458>
> > 
> > > .
> > 
> > ## 
> > 
> > Laura Billings
> > 
> > 07789 214 934
> > @laurabillings https://twitter.com/laurabillings
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45363386>
> > 
> > . <
> > 
> > https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxNzY5NTIyMywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--3ebe8632c6740dfc26fccfec2533943edc1d1d95.gif>
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45381243>
> > 
> > .
> 
> ## 
> 
> Laura Billings
> 
> 07789 214 934
> @laurabillings https://twitter.com/laurabillings
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45792309>
> . <
> https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxODEzNjI3MCwiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--5abe1336094c746e3a63c48f649264c9810a250d.gif>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-46185884
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings

**Comment by brittanyukulele** [comment]
Got it! I have changed it and you should be good. Have a great week!

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy http://twitter.com/tradeschoolindy 
(317) 366-6938

http://tradeschool.coop/Indianapolis http://tradeschool.coop/Indianapolis/class

**Comment by laurabillings** [comment]
awesome - thanks!

On Tue, Jun 24, 2014 at 2:23 PM, brittanyukulele notifications@github.com
wrote:

> Got it! I have changed it and you should be good. Have a great week!
> 
> Brittany West
> Co-Founder Trade School Indy / @tradeschoolindy <
> http://twitter.com/tradeschoolindy>
> (317) 366-6938
> 
> http://tradeschool.coop/Indianapolis <
> http://tradeschool.coop/Indianapolis/class>
> 
> From: laurabillings [mailto:notifications@github.com]
> Sent: Monday, June 23, 2014 7:07 AM
> To: orzubalsky/tradeschool
> Cc: brittanyukulele
> Subject: Re: [tradeschool] How to change main branch email? (#167)
> 
> hey Britanny
> 
> I added you to Westminster - can you see that?
> there were also a couple of Brittany usernames in the list, i might not
> have added the right one..?
> 
> On Mon, Jun 16, 2014 at 3:33 PM, brittanyukulele notifications@github.com
> 
> wrote:
> 
> > hey laura!
> > 
> > I don't see london as an option. :( I can also login to your backend if
> > you let me know your username/pw. Thank you!
> > 
> > Brittany West
> > Co-Founder Trade School Indy / @tradeschoolindy <
> > http://twitter.com/tradeschoolindy>
> > (317) 366-6938
> > 
> > http://tradeschool.coop/Indianapolis <
> > http://tradeschool.coop/Indianapolis/class>
> > 
> > From: laurabillings [mailto:notifications@github.com]
> > Sent: Wednesday, June 11, 2014 4:05 PM
> > To: orzubalsky/tradeschool
> > Cc: brittanyukulele
> > Subject: Re: [tradeschool] How to change main branch email? (#167)
> > 
> > done!
> > 
> > On Fri, Jun 6, 2014 at 9:33 PM, brittanyukulele <
> > notifications@github.com>
> > 
> > wrote:
> > 
> > > no prob!
> > > 
> > > in admin go to people > settings > branches > click on your branch >
> > > scroll down to organizers > find my name under available organizers >
> > > Brittany > add to chosen organizers
> > > 
> > > let me know when you do that and I will take a look!
> > > 
> > > From: laurabillings [mailto:notifications@github.com]
> > > Sent: Friday, June 06, 2014 1:34 PM
> > > To: orzubalsky/tradeschool
> > > Cc: brittanyukulele
> > > Subject: Re: [tradeschool] How to change main branch email? (#167)
> > > 
> > > Hey Brittany
> > > 
> > > Sorry - how do I do this?
> > > 
> > > On Mon, Jun 2, 2014 at 9:34 PM, brittanyukulele <
> > > notifications@github.com>
> > > 
> > > wrote:
> > > 
> > > > Hi Laura!
> > > > 
> > > > If you can add me as an organizer I can get in the backend and look
> > > > at
> > > > it
> > > > for ya! Thanks. :)
> > > > 
> > > > Brittany West
> > > > Co-Founder Trade School Indy / @tradeschoolindy <
> > > > http://twitter.com/tradeschoolindy>
> > > > (317) 366-6938
> > > > 
> > > > http://tradeschool.coop/Indianapolis <
> > > > http://tradeschool.coop/Indianapolis/class>
> > > > 
> > > > From: laurabillings [mailto:notifications@github.com]
> > > > Sent: Monday, May 26, 2014 3:27 AM
> > > > To: orzubalsky/tradeschool
> > > > Cc: brittanyukulele
> > > > Subject: Re: [tradeschool] How to change main branch email? (#167)
> > > > 
> > > > Thanks Brittany
> > > > 
> > > > The main email is showing as westminster@tradeschool.coop which is
> > > > currently diverting to tradeschoollondon@gmail.com. But we'd like
> > > > to
> > > > change
> > > > that to nkechi.ebite@hubwestminster.net
> > > > Not sure how to manage that?
> > > > Best
> > > > Laura
> > > > 
> > > > On Thu, May 15, 2014 at 9:34 PM, brittanyukulele
> > > > notifications@github.comwrote:
> > > > 
> > > > > Hey Laura!
> > > > > 
> > > > > In the admin backend go to 'branches' under settings > click your
> > > > > school
> > > > > 
> > > > > you can change your email address under contact info
> > > > > 
> > > > > let me now if that doesn't help. thank you!
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-43261352>
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Laura Billings
> > > > 
> > > > 07789 214 934
> > > > @laurabillings https://twitter.com/laurabillings
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44163843>
> > 
> > > > . <
> > 
> > https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxNjcwODQ0MywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--a26764b3bbe4e8da5a7ce907c32e3ec29ab2736d.gif>
> > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-44887458>
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Laura Billings
> > > 
> > > 07789 214 934
> > > @laurabillings https://twitter.com/laurabillings
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45363386>
> > 
> > > . <
> > 
> > https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxNzY5NTIyMywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--3ebe8632c6740dfc26fccfec2533943edc1d1d95.gif>
> > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45381243>
> > 
> > > .
> > 
> > ## 
> > 
> > Laura Billings
> > 
> > 07789 214 934
> > @laurabillings https://twitter.com/laurabillings
> > 
> > —
> > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-45792309>
> > 
> > . <
> > 
> > https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxODEzNjI3MCwiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--5abe1336094c746e3a63c48f649264c9810a250d.gif>
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-46185884>
> > 
> > .
> 
> ## 
> 
> Laura Billings
> 
> 07789 214 934
> @laurabillings https://twitter.com/laurabillings
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-46830712>
> . <
> https://github.com/notifications/beacon/5199620__eyJzY29wZSI6Ik5ld3NpZXM6QmVhY29uIiwiZXhwaXJlcyI6MTcxOTE0MDgwNywiZGF0YSI6eyJpZCI6MzIwMjE1NDN9fQ==--0bd1cb1bd18a30b88da285a3387d36b475482e1c.gif>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orzubalsky/tradeschool/issues/167#issuecomment-46969722
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings
