### ISSUE TITLE
unique URLs no longer working

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#174]
:(

**Comment by orzubalsky** [comment]
are you getting an error? is this for one class or more? it'll be helpful to get some more information :) 

thanks!

**Comment by brittanyukulele** [comment]
I figured it out. I guess that I was forgetting the / ! 

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy http://twitter.com/tradeschoolindy 
(317) 366-6938

http://tradeschool.coop/Indianapolis http://tradeschool.coop/Indianapolis/class
