### ISSUE TITLE
Reminder emails going out at wrong time/ not going out

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#175]
Hey guys - TS Westminster got in touch because they just got reminder emails for a class that happened last week... and TS West Norwood didn't send reminder emails out for the last class. We have checked that the start and end date are correct on the admin end. Is there something strange happening with the emails...? Thanks!

**Comment by brittanyukulele** [comment]
hey laura!
ive looked at both schools and can't seem to find any problems. ours are
working fine. if this continues to happen let me know and i can try and do
a test class to try and figure out whats going on. thank you!

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy
http://twitter.com/tradeschoolindy
(317) 366-6938
http://tradeschool.coop/Indianapolis
http://tradeschool.coop/Indianapolis/class

**Comment by michellesoto** [comment]
Hello everyone,  we have the same problem at ts quito. We've had to stop using the automatic emails because they are sent at random times or not sent at all. any ideas of what could be happening? not sure if we are doing something wrong?

Michelle Soto
La Trueca
