### ISSUE TITLE
Photos that are deleted via the webadmin interface might not actually be deleted?

### ISSUE THREAD

**Issue by ben41** [orzubalsky/tradeschool#176]
Photos that are deleted via the webadmin interface (http://tradeschool.coop/admin/tradeschool/photo/) are removed from the list of photos, but might not bey deleted from the database/filesystem.  When attempting to add a photo that has the same name as the one that was deleted, the new photo's filename gets changed to [name of photo]_1.jpg.   Now, this is not usually an issue as we don't change photos too often. However, I've rebuilt the HTML for the volunteers page for Indianapolis about 10 times and need to be able to delete photos each time it's rebuilt and upload new photos with the same file name. Otherwise, I have to bulk rename ~15 photos and change the HTML every time a new version is built.

**Comment by ghost** [comment]
This issue was moved to Z1800000000/tradeschool#10
