### ISSUE TITLE
Past dates showing in class slot drop down box

### ISSUE THREAD

**Issue by laurabillings** [orzubalsky/tradeschool#179]
Hi there
there are past dates showing up in the list of possible class options when a teacher signs up...
Thanks!
Screen shot attached
![screen shot 2014-09-10 at 12 26 47](https://cloud.githubusercontent.com/assets/6553938/4216700/a0d05056-38dd-11e4-8785-f8b2dbe1c7f4.png)

**Comment by RachL** [comment]
Hi @laurabillings !

Hope you are doing fine. In order for the past dates to disappear,  you have to delete them by yourself here:

http://tradeschool.coop/admin/tradeschool/time/

Just select them and in the footer you can choose the "delete" option.

We are doing this regularly. Tell me if it works on your side.

Cheers ;)

**Comment by laurabillings** [comment]
That works thank you!

On Wed, Sep 10, 2014 at 12:54 PM, RachL notifications@github.com wrote:

> Hi @laurabillings https://github.com/laurabillings !
> 
> Hope you are doing fine. In order for the past dates to disappear, you
> have to delete them by yourself here:
> 
> http://tradeschool.coop/admin/tradeschool/time/
> 
> Just select them and in the footer you can choose the "delete" option.
> 
> We are doing this regularly. Tell me if it works on your side.
> 
> Cheers ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orzubalsky/tradeschool/issues/179#issuecomment-55104537
> .

## 

Laura Billings

07789 214 934
@laurabillings https://twitter.com/laurabillings
