### ISSUE TITLE
Adding organizers to Branches

### ISSUE THREAD

**Issue by xthian** [orzubalsky/tradeschool#54]
When creating branches and adding organizers to it, it’s a bit confusing. Perhaps a better structure for this?

**Comment by orzubalsky** [comment]
changed the select widget to a horizontal one, i think this one is clearer.

**Comment by RachL** [comment]
Hi Or,

I wanted to help Trade School Geneva, so Narmada added me to her backend. Although I'm listed as one of the organizers on her backend, I don't manage to access it through my backend. Did we missed one step?

Thanks,

Rachel

**Comment by orzubalsky** [comment]
@RachL, when you log in to the admin, click on the school name on the top red bar. Is Geneva listed there? if it is, select it and click on "switch branch". That should change the context of the admin to that of the Geneva school. 

Let me know if it works!

**Comment by RachL** [comment]
Hi Or, yes thanks! It's working perfectly, I just had to reload the page :)
