### ISSUE TITLE
Printing (sending?) emails.

### ISSUE THREAD

**Issue by xthian** [orzubalsky/tradeschool#58]
The system is not printing all e-mails that it should be sending.

**Comment by orzubalsky** [comment]
@xthian, was this happening to all emails or a specific one? it seems to be sending emails when i use it so i could use more details to be able to investigate :)

**Comment by xthian** [comment]
I honestly don't remember what this was about...

**Comment by orzubalsky** [comment]
that's okay, so I'm closing this for now and we can reopen it if something comes up. we should try to put in as many details as we can when adding issues, it usually helps a lot!
