### ISSUE TITLE
new organizers need a login and password

### ISSUE THREAD

**Issue by carolinewoolard** [orzubalsky/tradeschool#62]
When I go to open a new branch for someone, and make a new user*, there's no way for this new person to login because there's no place to make a login or a password! I need some way for them to become an admin with a login and a password, so I can watch them use the backend as I talk them through using the site.

*
http://tradeschool.coop/admin/tradeschool/pendingbranch/add/

**Comment by orzubalsky** [comment]
Creating a new organizer should work now. The organizer would have to set their own password by going to http://tradeschool.coop/admin/password_reset
