### ISSUE TITLE
Cannot add multiple time slots

### ISSUE THREAD

**Issue by narmada4us** [orzubalsky/tradeschool#63]
What happened? I clicked on add many time slots and I got this error. 

KeyError at /admin/tradeschool/timerange/add/
'initial'
Request Method: GET
Request URL:    http://tradeschool.coop/admin/tradeschool/timerange/add/
Django Version: 1.5.1
Exception Type: KeyError
Exception Value:  
'initial'
Exception Location: /opt/projects/tse/ts/apps/tradeschool/admin.py in filter_dbfield, line 122
Python Executable:  /usr/bin/python
Python Version: 2.7.3
Python Path:  
['/opt/projects/tse/eggs/MySQL_python-1.2.3-py2.7-linux-x86_64.egg',
 '/opt/projects/tse/eggs/South-0.8.4-py2.7.egg',
 '/opt/projects/tse/eggs/simplejson-3.3.2-py2.7-linux-x86_64.egg',
 '/opt/projects/tse/eggs/PIL-1.1.7-py2.7-linux-x86_64.egg',
 '/opt/projects/tse/eggs/requests-2.2.1-py2.7.egg',
 '/opt/projects/tse/eggs/django_tinymce-1.5.2-py2.7.egg',
 '/opt/projects/tse/eggs/django_flatpages_tinymce-0.1.1-py2.7.egg',
 '/opt/projects/tse/eggs/pytz-2013.9-py2.7.egg',
 '/opt/projects/tse/eggs/django_countries-1.5-py2.7.egg',
 '/opt/projects/tse/eggs/django_grappelli-2.4.8-py2.7.egg',
 '/opt/projects/tse/eggs/feedparser-5.1.3-py2.7.egg',
 '/opt/projects/tse/eggs/django_dajaxice-0.5.5-py2.7.egg',
 '/opt/projects/tse/eggs/python_memcached-1.53-py2.7.egg',
 '/opt/projects/tse/eggs/six-1.5.2-py2.7.egg',
 '/opt/projects/tse/eggs/selenium-2.39.0-py2.7.egg',
 '/opt/projects/tse/eggs/docutils-0.11-py2.7.egg',
 '/opt/projects/tse/eggs/django_debug_toolbar-1.0.1-py2.7.egg',
 '/opt/projects/tse/eggs/django_tastypie-0.9.16-py2.7.egg',
 '/opt/projects/tse/eggs/django_ace-1.0.0-py2.7.egg',
 '/opt/projects/tse/eggs/djangorecipe-1.7-py2.7.egg',
 '/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg',
 '/opt/projects/tse/eggs/zc.recipe.egg-2.0.1-py2.7.egg',
 '/opt/projects/tse/eggs/zc.buildout-2.2.1-py2.7.egg',
 '/opt/projects/tse/eggs/python_dateutil-2.2-py2.7.egg',
 '/opt/projects/tse/eggs/mimeparse-0.1.3-py2.7.egg',
 '/opt/projects/tse/eggs/sqlparse-0.1.10-py2.7.egg',
 '/opt/projects/tse/eggs/setuptools-2.1-py2.7.egg',
 '/opt/projects/tse',
 '/opt/projects/tse/ts',
 '/opt/projects/tse/ts/apps',
 '/opt/projects/tse/parts/django-mailer',
 '/opt/projects/tse/parts/django-chunks',
 '/opt/projects/tse/parts/django-rosetta',
 '/opt/projects/tse/parts/django-rosetta-grappelli',
 '/opt/projects/tse/parts/django-admin-enhancer',
 '/opt/projects/tse/parts/django-admin-enhancer/admin_enhancer',
 '/opt/projects/tse/parts/django-guardian',
 '/opt/projects/tse/parts/johnny-cache',
 '/opt/projects/tse/parts/django-templatesadmin',
 '/opt/projects/tse',
 '/opt/projects/tse/ts',
 '/usr/local/lib/python2.7/dist-packages/distribute-0.7.3-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/setuptools-2.1-py2.7.egg',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/opt/projects/tse/ts/settings',
 '/opt/projects/tse/ts/settings/..',
 '/opt/projects/tse/ts/settings/../apps',
 '/opt/projects/tse/ts/settings/../libs']
Server time:    Sun, 26 Jan 2014 15:49:27 -0500
Traceback Switch to copy-and-paste view

/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/core/handlers/base.py in get_response
                        response = callback(request, _callback_args, *_callback_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/contrib/admin/options.py in wrapper
                return self.admin_site.admin_view(view)(_args, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/contrib/admin/sites.py in inner
            return view(request, _args, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/utils/decorators.py in _wrapper
            return bound_func(_args, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/utils/decorators.py in bound_func
                return func(self, _args2, *_kwargs2) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/db/transaction.py in inner
                return func(_args, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/contrib/admin/options.py in add_view
        ModelForm = self.get_form(request) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/contrib/admin/options.py in get_form
        return modelform_factory(self.model, **defaults) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/forms/models.py in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/forms/models.py in __new__
                                      opts.exclude, opts.widgets, formfield_callback) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/forms/models.py in fields_for_model
            formfield = formfield_callback(f, *_kwargs) ...
▶ Local vars
/opt/projects/tse/parts/django-admin-enhancer/admin_enhancer/admin.py in formfield_for_dbfield
        formfield = super(EnhancedAdminMixin, self).formfield_for_dbfield(db_field, *_kwargs) ...
▶ Local vars
/opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/contrib/admin/options.py in formfield_for_dbfield
                formfield = self.formfield_for_foreignkey(db_field, request, **kwargs) ...
▶ Local vars
/opt/projects/tse/ts/apps/tradeschool/admin.py in formfield_for_foreignkey
                    branch=request.user.default_branch ...
▶ Local vars
/opt/projects/tse/ts/apps/tradeschool/admin.py in filter_dbfield
        return kwargs['queryset'], kwargs['initial'] ...
▶ Local vars
Request information

GET
No GET data
POST
No POST data
FILES
No FILES data
COOKIES
Variable    Value
csrftoken  
'nAXcHJWKDamMgRnPRsRC0ft4Hsdi3mQs'
**utma  
'131219530.1681652818.1381341148.1381341148.1381341148.1'
__utmz  
'131219530.1381341148.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
sessionid  
'9hfcepmnkmhf8c96p9nwac9m5oqougb8'
META
Variable    Value
mod_wsgi.listener_port  
'80'
HTTP_COOKIE 
'__utma=131219530.1681652818.1381341148.1381341148.1381341148.1; __utmz=131219530.1381341148.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); csrftoken=nAXcHJWKDamMgRnPRsRC0ft4Hsdi3mQs; sessionid=9hfcepmnkmhf8c96p9nwac9m5oqougb8'
mod_wsgi.listener_host  
''
SERVER_SOFTWARE 
'Apache/2.2.22 (Ubuntu)'
SCRIPT_NAME 
u''
mod_wsgi.handler_script 
''
SERVER_SIGNATURE  
'<address>Apache/2.2.22 (Ubuntu) Server at tradeschool.coop Port 80</address>\n'
REQUEST_METHOD  
'GET'
PATH_INFO  
u'/admin/tradeschool/timerange/add/'
SERVER_PROTOCOL 
'HTTP/1.1'
QUERY_STRING  
''
HTTP_USER_AGENT 
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/6.1.1 Safari/537.73.11'
HTTP_CONNECTION 
'keep-alive'
HTTP_REFERER  
'http://tradeschool.coop/admin/'
SERVER_NAME 
'tradeschool.coop'
REMOTE_ADDR 
'178.193.80.160'
mod_wsgi.request_handler  
'wsgi-script'
wsgi.url_scheme 
'http'
PATH_TRANSLATED 
'/opt/projects/tse/bin/django.wsgi/admin/tradeschool/timerange/add/'
SERVER_PORT 
'80'
wsgi.multiprocess  
False
mod_wsgi.input_chunked  
'0'
SERVER_ADDR 
'107.170.26.231'
DOCUMENT_ROOT  
'/opt/projects/tse/ts'
mod_wsgi.process_group  
'tse_prod'
SCRIPT_FILENAME 
'/opt/projects/tse/bin/django.wsgi'
SERVER_ADMIN  
'or@tradeschool.coop'
wsgi.input  
<mod_wsgi.Input object at 0x7f68a53092f0>
HTTP_DNT  
'1'
HTTP_HOST  
'tradeschool.coop'
wsgi.multithread  
True
mod_wsgi.callable_object  
'application'
REQUEST_URI 
'/admin/tradeschool/timerange/add/'
HTTP_ACCEPT 
'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8'
wsgi.version  
(1, 1)
GATEWAY_INTERFACE  
'CGI/1.1'
wsgi.run_once  
False
wsgi.errors 
<mod_wsgi.Log object at 0x7f68a5309e30>
REMOTE_PORT 
'62958'
HTTP_ACCEPT_LANGUAGE  
'en-us'
mod_wsgi.version  
(3, 3)
mod_wsgi.application_group  
'tradeschool.coop|'
mod_wsgi.script_reloading  
'1'
wsgi.file_wrapper  
''
CSRF_COOKIE 
u'nAXcHJWKDamMgRnPRsRC0ft4Hsdi3mQs'
HTTP_ACCEPT_ENCODING  
'gzip, deflate'
Settings
Using settings module ts.settings.server
Setting Value
LOCAL_SETTINGS  
True
GRAPPELLI_INDEX_DASHBOARD  
'ts.dashboard.CustomIndexDashboard'
USE_L10N  
True
USE_THOUSAND_SEPARATOR  
False
CSRF_COOKIE_SECURE  
False
LANGUAGE_CODE  
'en-US'
ROOT_URLCONF  
'ts.urls'
MANAGERS  
(('Or Zubalsky', 'juviley@gmail.com'),)
DEFAULT_CHARSET 
'utf-8'
STATIC_ROOT 
'/opt/projects/tse/ts/static/'
TEMPLATESADMIN_TEMPLATE_DIRS  
('/opt/projects/tse/ts/settings/../apps/branches/',)
ALLOWED_HOSTS  
('.tradeschool.coop',)
MESSAGE_STORAGE 
'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX  
'[Django] '
SEND_BROKEN_LINK_EMAILS 
False
STATICFILES_FINDERS 
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder',
 'django.contrib.staticfiles.finders.DefaultStorageFinder',
 'dajaxice.finders.DajaxiceFinder')
SESSION_CACHE_ALIAS 
'default'
SESSION_COOKIE_DOMAIN  
None
SESSION_COOKIE_NAME 
'sessionid'
ADMIN_FOR  
()
TIME_INPUT_FORMATS  
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M', '%I:%M %p')
DATABASES  
{'default': {'ENGINE': 'django.db.backends.mysql',
             'HOST': '',
             'NAME': 'tradeschool_prod',
             'OPTIONS': {},
             'PASSWORD': u'*******************_',
             'PORT': '',
             'TEST_CHARSET': None,
             'TEST_COLLATION': None,
             'TEST_MIRROR': None,
             'TEST_NAME': None,
             'TIME_ZONE': 'UTC',
             'USER': 'tradeschooler'}}
FILE_UPLOAD_PERMISSIONS 
None
FILE_UPLOAD_HANDLERS  
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE  
'text/html'
APPEND_SLASH  
True
FIRST_DAY_OF_WEEK  
0
DATABASE_ROUTERS  
[]
YEAR_MONTH_FORMAT  
'F Y'
STATICFILES_STORAGE 
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES  
{'default': {'BACKEND': 'johnny.backends.memcached.MemcachedCache',
             'JOHNNY_CACHE': True,
             'LOCATION': ['127.0.0.1:11211']}}
SERVER_EMAIL  
'no-reply@theyoungest.webfactional.com'
SESSION_COOKIE_PATH 
'/'
MIDDLEWARE_CLASSES  
('johnny.middleware.LocalStoreClearMiddleware',
 'johnny.middleware.QueryCacheMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'tradeschool.middleware.BranchMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware')
USE_I18N  
True
THOUSAND_SEPARATOR  
','
SECRET_KEY  
u'**_*****************'
LANGUAGE_COOKIE_NAME  
'django_language'
FILE_UPLOAD_TEMP_DIR  
None
TRANSACTIONS_MANAGED  
False
LOGGING_CONFIG  
'django.utils.log.dictConfig'
TEMPLATE_LOADERS  
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
WSGI_APPLICATION  
None
TEMPLATE_DEBUG  
True
X_FRAME_OPTIONS 
'SAMEORIGIN'
AUTHENTICATION_BACKENDS 
('django.contrib.auth.backends.ModelBackend',)
FORCE_SCRIPT_NAME  
None
USE_X_FORWARDED_HOST  
False
SIGNING_BACKEND 
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE  
False
CSRF_COOKIE_DOMAIN  
None
FILE_CHARSET  
'utf-8'
DEBUG  
True
SESSION_FILE_PATH  
None
DEFAULT_FILE_STORAGE  
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS  
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'grappelli.dashboard',
 'grappelli',
 'rosetta-grappelli',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.humanize',
 'django.contrib.redirects',
 'django.contrib.flatpages',
 'flatpages_tinymce',
 'django_ace',
 'templatesadmin',
 'south',
 'pytz',
 'dajaxice',
 'rosetta',
 'admin_enhancer',
 'tastypie',
 'tradeschool',
 'migration')
LANGUAGES  
(('en', 'English'),
 ('es_es', 'Spanish (Spain)'),
 ('es_mx', 'Spanish (Mexico)'),
 ('es_us', 'Spanish (US)'),
 ('es_ar', 'Spanish (Argentina)'),
 ('es_cl', 'Spanish (Chile)'),
 ('es_ec', 'Spanish (Ecuador)'),
 ('es_pr', 'Spanish (Puerto Rico)'),
 ('es_ve', 'Spanish (Venezuela)'),
 ('de_de', 'German'),
 ('ms_sg', 'Malay'),
 ('zh_sg', 'Chinese (Singapore)'),
 ('it_it', 'Italian'),
 ('tl', 'Tagalog'),
 ('fr_fr', 'French'),
 ('nl_nl', 'Dutch'),
 ('th', 'Thai'),
 ('pt_br', 'Portuguese'),
 ('el_gr', 'Greek'),
 ('ru_ru', 'Russian'),
 ('zh_cn', 'Chinese (China)'),
 ('vi', 'Vietnamese'),
 ('ta_sg', 'Tamil (Singapore)'))
COMMENTS_ALLOW_PROFANITIES  
False
STATICFILES_DIRS  
('/opt/projects/tse/ts/settings/../apps/branches',
 '/opt/projects/tse/ts/settings/../../parts/django-admin-enhancer/admin_enhancer/static')
PREPEND_WWW 
False
SECURE_PROXY_SSL_HEADER 
None
GRAPPELLI_ADMIN_TITLE  
<django.utils.functional.__proxy** object at 0x7f68ac688ed0>
SESSION_COOKIE_HTTPONLY 
True
DEBUG_PROPAGATE_EXCEPTIONS  
False
MONTH_DAY_FORMAT  
'F j'
LOGIN_URL  
'/admin'
SESSION_EXPIRE_AT_BROWSER_CLOSE 
False
TIME_FORMAT 
'P'
TEMPLATESADMIN_GROUP  
'translators'
AUTH_USER_MODEL 
'tradeschool.Person'
DATE_INPUT_FORMATS  
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
CSRF_COOKIE_NAME  
'csrftoken'
EMAIL_HOST_PASSWORD 
u'*******************_'
ROSETTA_WSGI_AUTO_RELOAD  
True
STAGE_NAME  
'DEV'
PASSWORD_RESET_TIMEOUT_DAYS 
u'**_****************_'
CACHE_MIDDLEWARE_ALIAS  
'default'
SESSION_SAVE_EVERY_REQUEST  
False
ADMIN_MEDIA_PREFIX  
'/admin/media/'
NUMBER_GROUPING 
0
SESSION_ENGINE  
'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW  
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH  
'/'
ROSETTA_MESSAGES_PER_PAGE  
100
LOGIN_REDIRECT_URL  
'/accounts/profile/'
DECIMAL_SEPARATOR  
'.'
IGNORABLE_404_URLS  
()
LOCALE_PATHS  
('/opt/projects/tse/ts/settings/../locale/',)
JOHNNY_MIDDLEWARE_KEY_PREFIX  
u'**_****************_'
TEMPLATE_STRING_IF_INVALID  
''
BASE_BRANCH_TEMPLATE_DIR  
'/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_base'
LOGOUT_URL  
'/accounts/logout/'
EMAIL_USE_TLS  
False
FIXTURE_DIRS  
('/opt/projects/tse/ts/settings/../apps/tradeschool/fixtures',)
EMAIL_HOST  
'smtp.webfaction.com'
DATE_FORMAT 
'N j, Y'
MEDIA_ROOT  
'/opt/projects/tse/ts/media/'
DEFAULT_EXCEPTION_REPORTER_FILTER  
'django.views.debug.SafeExceptionReporterFilter'
ADMINS  
(('Or Zubalsky', 'juviley@gmail.com'),)
FORMAT_MODULE_PATH  
None
DEFAULT_FROM_EMAIL  
'no-reply@tradeschool.coop'
MEDIA_URL  
'http://tradeschool.coop/media/'
DATETIME_FORMAT 
'N j, Y, P'
TEMPLATE_DIRS  
('/opt/projects/tse/ts/settings/../apps/branches/',
 '/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_default',
 '/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_base',
 '/opt/projects/tse/ts/settings/../apps/tradeschool/templates',
 '/opt/projects/tse/ts/settings/../templates',
 '/opt/projects/tse/ts/settings/../../parts/django-admin-enhancer/admin_enhancer/templates/')
SITE_ID 
1
DISALLOWED_USER_AGENTS  
()
ALLOWED_INCLUDE_ROOTS  
()
LOGGING 
{'disable_existing_loggers': False,
 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}},
 'handlers': {'console': {'class': 'logging.StreamHandler', 'level': 'DEBUG'},
              'mail_admins': {'class': 'django.utils.log.AdminEmailHandler',
                              'filters': ['require_debug_false'],
                              'level': 'ERROR'}},
 'loggers': {'dajaxice': {'handlers': ['console'],
                          'level': 'ERROR',
                          'propagate': True},
             'django.request': {'handlers': ['mail_admins'],
                                'level': 'ERROR',
                                'propagate': True}},
 'version': 1}
PROJECT_DIR 
'/opt/projects/tse/ts/settings/..'
TEST_RUNNER 
'django.test.simple.DjangoTestSuiteRunner'
SHORT_DATE_FORMAT  
'm/d/Y'
CACHE_MIDDLEWARE_KEY_PREFIX 
u'**_****************_'
TIME_ZONE  
'America/New_York'
FILE_UPLOAD_MAX_MEMORY_SIZE 
2621440
EMAIL_BACKEND  
'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_TABLESPACE  
''
TEMPLATE_CONTEXT_PROCESSORS 
('django.contrib.auth.context_processors.auth',
 'django.core.context_processors.request',
 'django.core.context_processors.i18n',
 'django.core.context_processors.debug',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.tz',
 'django.contrib.messages.context_processors.messages',
 'tradeschool.context_processors.branch')
SESSION_COOKIE_AGE  
1209600
SETTINGS_MODULE 
'ts.settings.server'
BRANCH_TEMPLATE_DIR 
'/opt/projects/tse/ts/settings/../apps/branches/'
USE_ETAGS  
False
LANGUAGES_BIDI  
('he', 'ar', 'fa')
DEFAULT_INDEX_TABLESPACE  
''
INTERNAL_IPS  
('127.0.0.1',)
STATIC_URL  
'http://tradeschool.coop/static/'
EMAIL_PORT  
25
USE_TZ  
True
SHORT_DATETIME_FORMAT  
'm/d/Y P'
PASSWORD_HASHERS  
u'**_****************_'
TINYMCE_DEFAULT_CONFIG  
{'plugins': 'table,spellchecker,paste,searchreplace', 'theme': 'advanced'}
ABSOLUTE_URL_OVERRIDES  
{}
CACHE_MIDDLEWARE_SECONDS  
600
DATETIME_INPUT_FORMATS  
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d %I:%M %p',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
DEFAULT_BRANCH_TEMPLATE_DIR 
'/opt/projects/tse/ts/settings/../apps/tradeschool/templates/branches_default'
ROSETTA_STORAGE_CLASS  
'rosetta.storage.SessionRosettaStorage'
EMAIL_HOST_USER 
'theyoungest'
PROFANITIES_LIST  
u'**_*****************'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by orzubalsky** [comment]
The problem was that there were no venues in the branch. The form tried to have an initial value of something, but there were no venues to choose from, so it broke. Now when there are no venues, the form just sets the venue value to an empty value.
