### ISSUE TITLE
Join Button

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#67]
-I have registered myself for several classes testing it out. When I click Join, nothing happens. And then when I click Join again after the first time with nothing happening, it says that 'You are already registered to this class'. So, I guess the issue it it's not working the first time you click it?

**Comment by orzubalsky** [comment]
What happens is that you are in fact being registered (hence the "already registered" message later) but you are not getting any visual indication that the system is processing your request after you clicked on join. We should add a loading animation to let you know that registration is taking place.

**Comment by orzubalsky** [comment]
a3bfd80f5e47474e9c859bbec868ee98774d1b07
