### ISSUE TITLE
Class Size (Already Registered)

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#70]
There is nothing that says how many students are registered in the classes when you are looking at the class. It only says the maximum number of seats, but there's no good way to tell where we are at size wise or how many seats are left. 
![bug](https://f.cloud.github.com/assets/5199620/2010669/d55144c6-8770-11e3-9d54-5aedce042e74.png)

**Comment by orzubalsky** [comment]
This is an easy thing to add and I bet it will be useful to other schools as well, thanks!
