### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#71]
From our GA friend Jenny!

Hi Or,

Brittany and I have been discussing some of the digital opportunities for the Trade School here in Indianapolis. And we were wondering if you might be able to help us out a little with our Google Analytic account.

From what we can tell, it looks like right now the GA tracking code is only catching the /Indianapolis/Newsletter page. To be honest, I'm a little confused about how the URIs work within tradeschool.coop, and I'm not actually sure this URI represents the Newsletter page. But we can save that conversation for later. For now, would you mind checking to make sure the tracking code has been installed on all of the /Indianapolis pages? (I've included it below for reference.)

Also, if I understand correctly, tradeschool.coop will be switching to a new CMS soon, or something along those lines, perhaps? If for whatever reason it makes more sense to hold off on the tracking code updates until then, just let us know.

Thank you so much for your help! We appreciate immensely, really. 

Sincerely,

Jenny Walton

P.S. Not that it makes much of a difference, but I have a certification in Google Analytics. So, I can promise you that I understand what I'm looking at and am not sending you on arbitrary errands.  Thanks again!

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39356335-1', 'tradeschool.coop');
  ga('send', 'pageview');

</script>

**Comment by orzubalsky** [comment]
How about we added a text box in the branch's settings where you could paste your google analytics embed code so it's included in all of the branch's pages?

**Comment by brittanyukulele** [comment]
Yes, that would be perfect!!
