### ISSUE TITLE
Weird Admin Error

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#73]
This has occasionally happened a few times while trying to log in.

MultipleObjectsReturned at /admin/
get() returned more than one Person -- it returned 4! Lookup parameters were {'fullname': <django.utils.functional.SimpleLazyObject object at 0x7f68a530d110>}
Request Method: GET
Request URL:    http://tradeschool.coop/admin/
Django Version:  1.5.1
Exception Type:  MultipleObjectsReturned
Exception Value:  
get() returned more than one Person -- it returned 4! Lookup parameters were {'fullname': <django.utils.functional.SimpleLazyObject object at 0x7f68a530d110>}
Exception Location:  /opt/projects/tse/eggs/Django-1.5.1-py2.7.egg/django/db/models/query.py in get, line 393
Python Executable:  /usr/bin/python
Python Version: 2.7.3

**Comment by orzubalsky** [comment]
This was fixed in this commit  4a371fb27031532706cd303934369ff0f0b966cd.
