### ISSUE TITLE
Cannot Delete Old Venues

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#74]
"Deleting the selected Venue would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:"

![bug3](https://f.cloud.github.com/assets/5199620/2010976/768657d4-8774-11e3-8663-42e62b8515e5.png)

**Comment by orzubalsky** [comment]
I'll look into this. In the meantime you can check off the "is active" option next to the venue at http://tradeschool.coop/admin/tradeschool/venue/. That would prevent it from being visible on the front end and will remove it from the admin backend's options in the different forms.
