### ISSUE TITLE
Add Barter Items - Barter Items Page

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#75]
I am trying to add a class that I accidentally deleted and I do not see anywhere where I can add a barter item. Upon looking at the approved classes, I do not see where I can even delete or change the barter items?

Here: http://tradeschool.coop/admin/tradeschool/barteritem/ there is nothing that says 'Add' or 'Edit' Barter item either, and the 'add' button is missing from the home admin page.

It just says 'Barter Item' & 'Title'. For our Indianapolis Basic Sewing 101 course.

**Comment by brittanyukulele** [comment]
If this can be high, that would be great. For some reason a few of our classes I must have deleted. And I have no idea how to add barter items to their class for registration.

**Comment by orzubalsky** [comment]
The permissions on barter item editing was set wrong, adding and editing is now available.

**Comment by brittanyukulele** [comment]
YAY!! You are my hero.
