### ISSUE TITLE
Editing more than one teacher for a class

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#78]
I cannot figure out how to edit the teacher of the class. All of our classes that had two teachers for some reason removed the second one.

**Comment by orzubalsky** [comment]
Can you try to find the email that the teachers submitted the class with? You might need to edit that teacher's information to include both names. Let me know how it goes.

**Comment by brittanyukulele** [comment]
I can change it that way, yep. I guess my question is how can I have them have a seperate thing? Once I added Danielle's name, now it says that we both taught all four classes that I hosted. If that makes sense.

**Comment by brittanyukulele** [comment]
I am having a lot of issues with this. Example: Toni Macri-Reiner has taught several classes for us. For this semester, she is teaching a joint class with Joanne Schmidt AND another class just by herself. I cannot edit the teachers information to reflect this. All of her classes now say she is joint teaching with Joanne. I cannot find how to edit who is teaching the class to reflect a separate teacher for them. Thoughts? Thanks!!

**Comment by orzubalsky** [comment]
Right, since we're using the same teacher information in all of the classes they teach, the name and bio is the same. The way to fix this would be to add a feature of having more than one teacher teaching a class. Is it okay if for now it will only be possible to change on the backend?

**Comment by brittanyukulele** [comment]
Yep, I just don't get how to edit it.

**Comment by orzubalsky** [comment]
This is the same issue as the one you opened on #66. I'm closing that one and we can continue to talk about it over here.
