### ISSUE TITLE
'Add Another Registration' Button doesn't work

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#79]
This is what it is showing:

(None)
(None)
Registered

How do you edit that?

**Comment by orzubalsky** [comment]
Oh yes, you're right. Is this something you find yourself doing often? I'm asking so I can prioritize this with the other issues.

**Comment by brittanyukulele** [comment]
I can always register them from the mainpage of our website, but it would be nice to use eventually! Def. low priority.
