### ISSUE TITLE
Save button for translation does not work twice in a row

### ISSUE THREAD

**Issue by RachL** [orzubalsky/tradeschool#80]
Actually it only works if I do the following:

Home > Translate TS > French > TS > "write translation" > save

If I save and then continue translation and save again, what I've translated between the two save actions is not saved. Is it normal?

I'm using the latest version of Firefox.

**Comment by orzubalsky** [comment]
There was a problem with the way the file permissions were set on the server. I fixed it and it should work now.

**Comment by RachL** [comment]
thanx :)
