### ISSUE TITLE
Class Time still messed up

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#81]
Hey Or,
Now the regular class times are saying something way off than what they should be. Am I just going to have to redo the class times for each class?

![bug](https://f.cloud.github.com/assets/5199620/2033517/f6b839f4-891d-11e3-888e-0df7a2736809.png)

**Comment by brittanyukulele** [comment]
figured this out! i changed my timezone to GMT +5 and it went back to normal times. But it would be awesome if I could get a quick explanation as to how I figured that out haha. When I researched GMT it said Indianapolis should be -5, but that was way off. Thanks!!

**Comment by brittanyukulele** [comment]
Nevermind, when I changed the time zone to +5, it reset the OTHER times again - the times when you click on a class to join.

**Comment by orzubalsky** [comment]
Yay! So are all the times correct now?

**Comment by brittanyukulele** [comment]
I don't think so. My classes still all say this when  I click join/

I would like to join
Yarn Scavenging
11:30p.m. to 1:00a.m.<--- Wrong time
at INRC at 1802 N Illinois St, Indianapolis

13 seats left
I can bring the following:
 Gluten Free Vegetarian Snacks & Treats
 Handmade Soap
 Organic Chocolate
 Sketchbook/Journals
Your name
