### ISSUE TITLE
Resetting Email Notifications

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#82]
I am not seeing how I can change the email notifications. I edited it in the Branch settings page, but it won't reflect on the classes I already have in the system. Unless I just have to copy and paste? in the old system I know there was a reset option.

![bug1](https://f.cloud.github.com/assets/5199620/2033571/c43c4956-891e-11e3-92aa-1c09d5d47d3e.png)
![bug2](https://f.cloud.github.com/assets/5199620/2033572/c54588e4-891e-11e3-9103-d4eefc12f05b.png)

**Comment by orzubalsky** [comment]
When you edit the branch's emails it will only apply to new classes that are added to the system. If you want to reset the emails for classes that have already been added, select them and choose "generate email notifications" on the bottom drop down menu.

![screen shot 2014-01-31 at 11 19 17 pm](https://f.cloud.github.com/assets/1025973/2056915/46989df2-8af8-11e3-9ebf-046c0fc61092.png)
