### ISSUE TITLE
Weird Email Language

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#83]
Welcome to Trade School!

You are successfully enrolled in "Weekly Conversation 4: Methods for Choosing & amp ; Starting Projects". Class will be held at Big Car at 3819 Lafayette Rd, Indianapolis and you agreed to barter New/Used Books for our Indoor & amp ; Outdoor Library

Do you know why it is saying "& amp ;" for all of our &s?

**Comment by orzubalsky** [comment]
This means the email form is creating html (&amp; is the html symbol for &), but the emails are sent as plain text. This should be an easy fix.

**Comment by orzubalsky** [comment]
Fixed!
