### ISSUE TITLE
'Add Organizers" and "Add teacher" buttons do not work

### ISSUE THREAD

**Issue by RachL** [orzubalsky/tradeschool#84]
Hi Or,

I've tried to add organizers and teachers. For both I've a notification that tells me it has worked, but I can't see the added teacher or organizer on the page, even after refreshing...

Many thanks in advance for your feedback!

Rachel A.

**Comment by orzubalsky** [comment]
What happens when you create a new one and click on "save and continue editing"? If there's an error screen, would you mind attaching a screenshot here?

**Comment by RachL** [comment]
This is what happen when I click save:
http://awesomescreenshot.com/0e92a3vc78 (=> good message, but no action, even in the Branches info, I don't see the new organizer's name, but it seems that the info is saved somewhere as I cannot enter the same name twice).

This is what happens when I click "save and continue editing":
http://awesomescreenshot.com/0ff2a3vo75

Both for the teacher and organizers button. 

PS: to enlarge the screenshots just click on them

**Comment by orzubalsky** [comment]
Adding an organizer is working now. 

I'm still working on the add teacher bug. Do you often add teachers through the admin or do you accept class submissions through the website?

**Comment by brittanyukulele** [comment]
We use a separate form for submissions, finalize all of the classes, and then input them into the website ourselves.

**Comment by eaguilar1** [comment]
![image](https://f.cloud.github.com/assets/6555730/2052901/06725402-8a9e-11e3-83c3-b2a3841059a9.jpg)

I can't input a new class in the front end and also can't from the back end :(

**Comment by orzubalsky** [comment]
adding a teacher should work now :)
