### ISSUE TITLE
"Delete selected organizers" button doesn't work

### ISSUE THREAD

**Issue by RachL** [orzubalsky/tradeschool#85]
It shows a "403 Forbidden" error after clicking on "save"

Low priority feature though ;)

**Comment by orzubalsky** [comment]
Hey Rachel, this issue was logged here before, take a look here- https://github.com/orzubalsky/tradeschool/issues/72

You can search the issues in the search box all the way at the top of this page. 

Thanks!

**Comment by RachL** [comment]
oups sorry about that !

**Comment by orzubalsky** [comment]
No worries. It's great that you're using github. It makes working on these bugs much easier!
