### ISSUE TITLE
Changing Students Name

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#90]
![change student trade school](https://f.cloud.github.com/assets/5199620/2041429/123d6404-89c5-11e3-80f7-acf168e0ac81.png)

I have no idea how to edit a students name, which is unfortunate because when we lost all of our classes, I wasn't sure of many of the names (guessed by emails) and I'm afraid when the emails get sent, they will all have the wrong name. 

Somehow, I end up at Home > People, and can change it.

![home-people](https://f.cloud.github.com/assets/5199620/2041529/4a5d5532-89c6-11e3-9e64-86d88c6668a3.png)

But there is no button for People, so I am not sure how I got there. From the homepage on the Admin site, I click Students, and that is where it is not letting me edit their name or anything.

![home-students](https://f.cloud.github.com/assets/5199620/2041543/6a049c92-89c6-11e3-9c38-936bdda10f16.png)

**Comment by orzubalsky** [comment]
The full name field is now a part of this form c0fa980032459a2bbe1b6880f9f0ec5d049b822c
