### ISSUE TITLE
'Add Teacher' Button

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#91]
I clicked both buttons below and put in their information, but it looks like it's not saving it as a teacher, but rather as a student/person?

![teacherbutton](https://f.cloud.github.com/assets/5199620/2042504/5629cfe2-89d2-11e3-9ec7-5d3e40e08d02.png)

![teacherbutton2](https://f.cloud.github.com/assets/5199620/2042562/f87a8156-89d2-11e3-9b3c-96047343042f.png)

**Comment by orzubalsky** [comment]
This issue is the same as #84, which Rachel from Paris submitted. I'm closing this one so all of the discussions are in one place. This will be the first time 2 organizers from different schools meet on github, yay!
