### ISSUE TITLE
'5 Barter Items'

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#92]
From Eduardo

Hello there, i'm sorry, someone can help me with this? the thing is that I cannot make a new class without five things, and we don't always ask at least five things... thank you

![1492632_10152179297264002_679137991_o](https://f.cloud.github.com/assets/5199620/2043493/949e9bb0-89df-11e3-982a-3eb5687fd9f9.jpg)

**Comment by orzubalsky** [comment]
Now you can set the minimum number of barter items that is required in this form. Set it by going to http://tradeschool.coop/admin/tradeschool/branch/, clicking on your branch, and set the minimum barter items:

![screen shot 2014-02-01 at 4 46 35 pm](https://f.cloud.github.com/assets/1025973/2058875/7fd545ec-8b8a-11e3-886c-a8d1eddd6569.png)
