### ISSUE TITLE
Automatic Emails Messing Up - Barter Items

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#95]
Here is your class list so far and what each student agreed to bring. Always plan for at least 2-3 more!

Anne-Marie Taylor: [, u, &#39;, G, l, u, t, e, n,  , F, r, e, e,  , V, e, g, e, t, a, r, i, a, n,  , S, n, a, c, k, s,  , &amp;,  , T, r, e, a, t, s, &#39;, ]
Bekka Sage: [, u, &#39;, O, r, g, a, n, i, c,  , C, h, o, c, o, l, a, t, e, &#39;, ]
candace matsumoto: [, u, &#39;, S, k, e, t, c, h, b, o, o, k, /, J, o, u, r, n, a, l, s, &#39;, ]
Cara Moczgyemba: [, ]
Heather Hall: [, ]
Jan Edmondson: [, u, &#39;, G, l, u, t, e, n,  , F, r, e, e,  , V, e, g, e, t, a, r, i, a, n,  , S, n, a, c, k, s,  , &amp;,  , T, r, e, a, t, s, &#39;, ]
Megan Hart: [, u, &#39;, G, l, u, t, e, n,  , F, r, e, e,  , V, e, g, e, t, a, r, i, a, n,  , S, n, a, c, k, s,  , &amp;,  , T, r, e, a, t, s, &#39;, ]
Megen Smith: [, u, &#39;, S, k, e, t, c, h, b, o, o, k, /, J, o, u, r, n, a, l, s, &#39;, ]
melissa hudson: [, ]
Regan Brown: [, u, &#39;, S, k, e, t, c, h, b, o, o, k, /, J, o, u, r, n, a, l, s, &#39;, ]
Sara Neitzel: [, u, &#39;, H, a, n, d, m, a, d, e,  , S, o, a, p,  , &#39;, ,,  , u, &#39;, S, k, e, t, c, h, b, o, o, k, /, J, o, u, r, n, a, l, s, &#39;, ]
Stephanie Koutek: [, u, &#39;, S, k, e, t, c, h, b, o, o, k, /, J, o, u, r, n, a, l, s, &#39;, ]

**Comment by orzubalsky** [comment]
I just fixed it, did you get an email with this problem in the past hour?

**Comment by brittanyukulele** [comment]
Oh nice! I just wanted to make sure I logged it for you. Thanks!! :)

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy
(317) 366-6938
http://tradeschool.coop/Indianapolishttp://tradeschool.coop/Indianapolis/class

**Comment by orzubalsky** [comment]
No problem, thank you!
