### ISSUE TITLE
New Teacher Bios

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#96]
![teacher](https://f.cloud.github.com/assets/5199620/2052138/9ffa6544-8a92-11e3-9ce0-e65633132ef6.png)

So, the new teachers are showing up as people rather than teachers. And I am not sure how to edit their bio or website?

**Comment by orzubalsky** [comment]
I've been working on fixing this, thanks for logging it!

**Comment by orzubalsky** [comment]
you can edit all teachers and their bios from the teachers list at http://tradeschool.coop/admin/tradeschool/teacher
