### ISSUE TITLE
Signing up to Teach a Class

### ISSUE THREAD

**Issue by harleytsberlin** [orzubalsky/tradeschool#98]
![screen shot 2014-02-01 at 9 30 15 pm](https://f.cloud.github.com/assets/6563654/2058717/47df25e0-8b80-11e3-9830-2aed54812fe4.png)

**Comment by orzubalsky** [comment]
Looks like someone edited the link at the bottom of your (Berlin's) teacher info page and the new link was broken. I edited the page's html content and fixed it. The URL to the class submission form is http://tradeschool.coop/school_name/class/add.

Let me know if you have any questions :)

**Comment by RachL** [comment]
Hi Or,

Same problem here in Paris, thanks for the new link!

However I don't seem to find where I can edit the content of the old "Want to teach a class" page in the backend. It was a full page with a "I want to teach" button at the end. After clicking on the button the potential teacher reached the link you just gave us.

Shall I just create a new page in "branche pages" ? Or does the page still exist somewhere?

Sorry if it has already been asked somewhere else. And thanks again for everything :)

**Comment by orzubalsky** [comment]
Hi Rachel! 

Yes, it looks like Paris doesn't have that page yet so you can create a new one and link to it. Let me know if you need help with any of these things.

**Comment by RachL** [comment]
Thanks for your quick feedback! One question though: is it still possible to create a button inside a page? I'm not sure of which html code is right.

One last question: how to show this page: http://tradeschool.coop/paris/class/add in French?

I've set the language of the branch to "french", but it doesn't seems enough. Is there something else to do?

**Comment by orzubalsky** [comment]
Do you mind opening another issue for the translation not working? I'll work on that over the weekend.

You can create a button in the html. We've been using this HTML for buttons:

<div class="subButtonBox"><a class="submit" href="../class/add">Sign up to teach</a></div>

**Comment by orzubalsky** [comment]
Oops- 

```
<div class="subButtonBox">    <a class="submit" href="../class/add">Sign up to teach</a></div>
```

**Comment by RachL** [comment]
Thanks Or, I will open another issue
