### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by brittanyukulele** [orzubalsky/tradeschool#99]
Now that we've figured out the website schtuff, I would love to mess with our web design! :)

Where would I put in custom CSS for the website? Where can I find the current code that makes the 'barter for knowledge' square orange and the pages yellow?

Thank you!!!

**Comment by orzubalsky** [comment]
you can add custom CSS to your school's pages:
1. log in to the admin section 
2. click on "edit HTML templates" on the right (it's in the links section).
3. edit the file "branch.css" that's in your school'a directory 
4. click on save when you're done. 

This is the last stylesheet that's loaded on your school's pages so rules you add there will override the default design.

Let me know how it goes!

**Comment by brittanyukulele** [comment]
/\* Add your branch's css here! */
<head>

<style>
hr {color:purple;}
p {margin-left:50px;}
body {background-color:#b0c4de;}
</style>

<h1>My CSS web page!</h1>

<p>Hello world! This is a W3Schools.com example.</p>

</head>

So I made all of those changes in where you said and I do not see where they are showing up?

**Comment by orzubalsky** [comment]
Is it up now?

**Comment by brittanyukulele** [comment]
Up where?

**Comment by orzubalsky** [comment]
On the Indianapolis pages

**Comment by brittanyukulele** [comment]
I do not see any changes reflecting what I wrote in the code. There is a
good chance that I didn't put in the correct CSS, but Im almost positive I
did

Brittany West
Co-Founder Trade School Indy / @tradeschoolindy
(317) 366-6938
http://tradeschool.coop/Indianapolishttp://tradeschool.coop/Indianapolis/class

**Comment by orzubalsky** [comment]
can you clear your browser's cache and check again?

**Comment by brittanyukulele** [comment]
just did. I am not seeing anything. just to confirm...this is what my current CSS code looks like 

![css](https://f.cloud.github.com/assets/5199620/2114166/edf0ac80-9038-11e3-859e-81242515b638.png)

**Comment by lpedante** [comment]
Hey, there! Just wanted to see if I could find answers here. The CSS to change the background color isn't having any affect on my side either...would love some input. Thanks! 

![css](https://f.cloud.github.com/assets/6611930/2191186/800e7418-983f-11e3-80da-4d2e0a78eacf.JPG)

**Comment by orzubalsky** [comment]
It turns out the system needs to run a script to refresh the changes that are saved on the admin backend. I ran it manually to confirm and I see the beautiful new background color! I'm currently working on fixing other issues but I'll get to this as well in time :) In the meantime, I can run the script  manually again whenever you're ready.

**Comment by lpedante** [comment]
Fantastic! Thank you!

**Comment by lpedante** [comment]
Hi, Or! Can you run the script to update a CSS change I made? Thanks!

**Comment by orzubalsky** [comment]
@lpedante- updated!

**Comment by orzubalsky** [comment]
From now on when you edit templates, css or js, the changes will be updated automatically when you save.
